package codegen

func GenerateClientRuntimeTS() string {
	return `// Code generated by rstf. DO NOT EDIT.
import { startTransition, useEffect, useRef, useState } from "react";

export type QueryDef<P, R> = {
  kind: "query";
  route: string;
  name: string;
};

export type MutationDef<P, I, R> = {
  kind: "mutation";
  route: string;
  name: string;
};

export type ActionDef<P, I, R> = {
  kind: "action";
  route: string;
  name: string;
};

type QueryStatus = "loading" | "ready" | "error";

type RPCResponse<T> = {
  data: T;
};

type RPCError = {
  code: string;
  message: string;
  details?: Record<string, unknown>;
};

type LiveEvent<T> =
  | { type: "query_result"; subscriptionId: string; data: T }
  | { type: "query_error"; subscriptionId: string; error: RPCError };

type LiveSubscribeRequest = {
  clientId: string;
  subscriptionId: string;
  route: string;
  name: string;
  params: Record<string, string>;
};

type LiveUnsubscribeRequest = {
  clientId: string;
  subscriptionId: string;
};

type RPCRequest = {
  kind: "mutation" | "action";
  route: string;
  name: string;
  params: Record<string, string>;
  input?: unknown;
};

type QueryState<T> =
  | { status: "loading"; data: null; error: null }
  | { status: "ready"; data: T; error: null }
  | { status: "error"; data: null; error: RPCError };

type QueryListener = (event: LiveEvent<unknown>) => void;

const listeners = new Map<string, QueryListener>();
const clientId = createClientId();
let source: EventSource | null = null;

function createClientId(): string {
  const random = Math.random().toString(36).slice(2);
  return "rstf_" + random;
}

function stableStringify(value: unknown): string {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return "[" + value.map((item) => stableStringify(item)).join(",") + "]";
  }
  const entries = Object.entries(value as Record<string, unknown>).sort(([a], [b]) =>
    a.localeCompare(b)
  );
  return (
    "{" +
    entries
      .map(([key, item]) => JSON.stringify(key) + ":" + stableStringify(item))
      .join(",") +
    "}"
  );
}

function ensureLiveConnection(): void {
  if (typeof window === "undefined" || source !== null) {
    return;
  }

  source = new EventSource("/__rstf/live?clientId=" + encodeURIComponent(clientId));
  source.onmessage = (event) => {
    const payload = JSON.parse(event.data) as LiveEvent<unknown>;
    const listener = listeners.get(payload.subscriptionId);
    if (listener) {
      listener(payload);
    }
  };
  source.onerror = () => {
    // EventSource handles reconnects automatically.
  };
}

async function postJSON<T>(url: string, body: unknown): Promise<T> {
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  let payload: any = null;
  try {
    payload = await response.json();
  } catch {
    payload = null;
  }

  if (!response.ok) {
    const err = payload?.error as RPCError | undefined;
    throw err ?? {
      code: "internal_error",
      message: "request failed",
    };
  }

  return payload as T;
}

async function subscribeQuery<P extends Record<string, string>, R>(
  def: QueryDef<P, R>,
  params: P,
  subscriptionId: string,
  listener: QueryListener
): Promise<R> {
  ensureLiveConnection();
  listeners.set(subscriptionId, listener);

  try {
    const response = await postJSON<RPCResponse<R>>("/__rstf/live/subscribe", {
      clientId,
      subscriptionId,
      route: def.route,
      name: def.name,
      params,
    } satisfies LiveSubscribeRequest);
    return response.data;
  } catch (error) {
    listeners.delete(subscriptionId);
    throw error;
  }
}

function unsubscribeQuery(subscriptionId: string): void {
  listeners.delete(subscriptionId);
  void postJSON<Record<string, boolean>>("/__rstf/live/unsubscribe", {
    clientId,
    subscriptionId,
  } satisfies LiveUnsubscribeRequest).catch(() => {
    // Best-effort cleanup only.
  });
}

export function defineQuery<P, R>(route: string, name: string): QueryDef<P, R> {
  return { kind: "query", route, name };
}

export function defineMutation<P, I, R>(route: string, name: string): MutationDef<P, I, R> {
  return { kind: "mutation", route, name };
}

export function defineAction<P, I, R>(route: string, name: string): ActionDef<P, I, R> {
  return { kind: "action", route, name };
}

export function useQuery<P extends Record<string, string>, R>(def: QueryDef<P, R>, params: P) {
  const subscriptionIdRef = useRef<string>("");
  if (!subscriptionIdRef.current) {
    subscriptionIdRef.current = "sub_" + Math.random().toString(36).slice(2);
  }

  const [state, setState] = useState<QueryState<R>>({
    status: "loading",
    data: null,
    error: null,
  });

  const paramsKey = stableStringify(params);
  useEffect(() => {
    let active = true;

    setState({
      status: "loading",
      data: null,
      error: null,
    });

    const listener: QueryListener = (event) => {
      if (!active) {
        return;
      }
      startTransition(() => {
        if (event.type === "query_result") {
          setState({
            status: "ready",
            data: event.data as R,
            error: null,
          });
          return;
        }
        setState({
          status: "error",
          data: null,
          error: event.error,
        });
      });
    };

    subscribeQuery(def, params, subscriptionIdRef.current, listener)
      .then((data) => {
        if (!active) {
          return;
        }
        startTransition(() => {
          setState({
            status: "ready",
            data,
            error: null,
          });
        });
      })
      .catch((error: RPCError) => {
        if (!active) {
          return;
        }
        startTransition(() => {
          setState({
            status: "error",
            data: null,
            error,
          });
        });
      });

    return () => {
      active = false;
      unsubscribeQuery(subscriptionIdRef.current);
    };
  }, [def, paramsKey]);

  return state;
}

export function useMutation<P extends Record<string, string>, I, R>(
  def: MutationDef<P, I, R>,
  params: P
) {
  return async (input: I): Promise<R> => {
    const response = await postJSON<RPCResponse<R>>("/__rstf/rpc", {
      kind: def.kind,
      route: def.route,
      name: def.name,
      params,
      input,
    } satisfies RPCRequest);
    return response.data;
  };
}

export function useAction<P extends Record<string, string>, I, R>(
  def: ActionDef<P, I, R>,
  params: P
) {
  return async (input: I): Promise<R> => {
    const response = await postJSON<RPCResponse<R>>("/__rstf/rpc", {
      kind: def.kind,
      route: def.route,
      name: def.name,
      params,
      input,
    } satisfies RPCRequest);
    return response.data;
  };
}
`
}
