package codegen

import (
	"fmt"
	"path/filepath"
	"strings"
)

// GenerateHydrationEntry produces the content of a hydration entry file
// (rstf/entries/{name}.entry.tsx) for a route directory.
//
// routeDir is the route directory relative to project root (e.g. "routes/dashboard").
// allDeps is currently unused by the hydration entry. It is retained because the
// generator still computes dependency lists for the Go SSR pass.
//
// The entry file is generated inside rstf/entries/, so relative imports use
// "../../" to reach the project root.
func GenerateHydrationEntry(routeDir string, allDeps []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")
	b.WriteString("import { hydrateRoot } from \"react-dom/client\";\n")
	b.WriteString("import { SSRDataProvider } from \"@rstf/ssr\";\n")
	b.WriteString("import { View as Layout } from \"../../main\";\n")
	fmt.Fprintf(&b, "import { View as Route } from \"../../%s\";\n", routeDir)
	_ = allDeps
	b.WriteString("\n")
	b.WriteString("const ssrProps = (window as any).__RSTF_SSR_PROPS__ ?? {};\n\n")
	b.WriteString("hydrateRoot(document, <SSRDataProvider data={ssrProps}><Layout><Route /></Layout></SSRDataProvider>);\n")
	return b.String()
}

// GenerateSSREntry produces the content of an SSR entry file
// (rstf/ssr_entries/{name}.ssr.tsx) for a route directory.
func GenerateSSREntry(routeDir string) string {
	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")
	b.WriteString("import { renderToString } from \"react-dom/server.browser\";\n")
	b.WriteString("import { SSRDataProvider } from \"@rstf/ssr\";\n")
	b.WriteString("import { View as Layout } from \"../../main\";\n")
	fmt.Fprintf(&b, "import { View as Route } from \"../../%s\";\n", routeDir)
	b.WriteString("\n")
	b.WriteString("const render = (ssrProps: Record<string, Record<string, any>>) =>\n")
	b.WriteString("  renderToString(<SSRDataProvider data={ssrProps}><Layout><Route /></Layout></SSRDataProvider>);\n\n")
	b.WriteString("(globalThis as any).__RSTF_RENDERERS__ = (globalThis as any).__RSTF_RENDERERS__ ?? {};\n")
	fmt.Fprintf(&b, "(globalThis as any).__RSTF_RENDERERS__[%q] = render;\n", routeDir)
	return b.String()
}

// entryName returns the entry file basename for a route directory.
//
//	"routes/dashboard"       → "dashboard"
//	"routes/index"           → "index"
//	"routes/users._id.edit"  → "users-id-edit"
func entryName(routeDir string) string {
	name := strings.TrimPrefix(routeDir, "routes/")
	return routeArtifactName(name)
}

// entryFileName returns the full filename for an entry file.
//
//	"routes/dashboard" → "dashboard.entry.tsx"
func entryFileName(routeDir string) string {
	return entryName(routeDir) + ".entry.tsx"
}

func ssrEntryFileName(routeDir string) string {
	return entryName(routeDir) + ".ssr.tsx"
}

// bundlePath returns the URL path for a route's client bundle.
//
//	"routes/dashboard" → "/rstf/static/dashboard/bundle.js"
func bundlePath(routeDir string) string {
	return filepath.ToSlash(filepath.Join("/rstf/static", entryName(routeDir), "bundle.js"))
}

func ssrBundlePath(routeDir string) string {
	return filepath.ToSlash(filepath.Join("rstf", "ssr", entryName(routeDir)+".js"))
}
