package codegen

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestGenerateHydrationEntry_Dashboard(t *testing.T) {
	got := GenerateHydrationEntry("routes/dashboard", []string{"routes/dashboard"})

	expectations := []string{
		"// Code generated by rstf. DO NOT EDIT.",
		`import { hydrateRoot } from "react-dom/client";`,
		`import { SSRDataProvider } from "@rstf/ssr";`,
		`import { View as Layout } from "../../main";`,
		`import { View as Route } from "../../routes/dashboard";`,
		`const ssrProps = (window as any).__RSTF_SSR_PROPS__ ?? {};`,
		`hydrateRoot(document, <SSRDataProvider data={ssrProps}><Layout><Route /></Layout></SSRDataProvider>);`,
	}

	for _, exp := range expectations {
		assert.Contains(t, got, exp, "output missing %q\n\nFull output:\n%s", exp, got)
	}
}

func TestGenerateHydrationEntry_WithSharedDeps(t *testing.T) {
	got := GenerateHydrationEntry("routes/dashboard", []string{"routes/dashboard", "shared/ui/user-avatar"})

	assert.NotContains(t, got, `import "@rstf/routes/dashboard";`)
	assert.NotContains(t, got, `import "@rstf/shared/ui/user-avatar";`)
}

func TestEntryName(t *testing.T) {
	tests := []struct {
		routeDir string
		want     string
	}{
		{"routes/dashboard", "dashboard"},
		{"routes/index", "index"},
		{"routes/users._id.edit", "users-id-edit"},
	}
	for _, tt := range tests {
		got := entryName(tt.routeDir)
		assert.Equal(t, tt.want, got, "entryName(%q)", tt.routeDir)
	}
}

func TestEntryFileName(t *testing.T) {
	got := entryFileName("routes/dashboard")
	assert.Equal(t, "dashboard.entry.tsx", got, "entryFileName")
}

func TestBundlePath(t *testing.T) {
	tests := []struct {
		routeDir string
		want     string
	}{
		{"routes/dashboard", "/rstf/static/dashboard/bundle.js"},
		{"routes/users._id.edit", "/rstf/static/users-id-edit/bundle.js"},
	}
	for _, tt := range tests {
		got := bundlePath(tt.routeDir)
		assert.Equal(t, tt.want, got, "bundlePath(%q)", tt.routeDir)
	}
}
