package codegen

import (
	"strings"
	"testing"
)

func TestGenerateHydrationEntry_Dashboard(t *testing.T) {
	got := GenerateHydrationEntry("routes/dashboard", []string{"routes/dashboard"})

	expectations := []string{
		"// Code generated by rstf. DO NOT EDIT.",
		`import { hydrateRoot } from "react-dom/client";`,
		`import { View as Layout } from "../../main";`,
		`import { View as Route } from "../../routes/dashboard";`,
		`import "@rstf/main";`,
		`import "@rstf/routes/dashboard";`,
		`hydrateRoot(document, <Layout><Route /></Layout>);`,
	}

	for _, exp := range expectations {
		if !strings.Contains(got, exp) {
			t.Errorf("output missing %q\n\nFull output:\n%s", exp, got)
		}
	}
}

func TestGenerateHydrationEntry_WithSharedDeps(t *testing.T) {
	got := GenerateHydrationEntry("routes/dashboard", []string{"routes/dashboard", "shared/ui/user-avatar"})

	expectations := []string{
		`import "@rstf/routes/dashboard";`,
		`import "@rstf/shared/ui/user-avatar";`,
	}

	for _, exp := range expectations {
		if !strings.Contains(got, exp) {
			t.Errorf("output missing %q\n\nFull output:\n%s", exp, got)
		}
	}
}

func TestEntryName(t *testing.T) {
	tests := []struct {
		routeDir string
		want     string
	}{
		{"routes/dashboard", "dashboard"},
		{"routes/index", "index"},
		{"routes/users.$id.edit", "users-id-edit"},
	}
	for _, tt := range tests {
		got := entryName(tt.routeDir)
		if got != tt.want {
			t.Errorf("entryName(%q) = %q, want %q", tt.routeDir, got, tt.want)
		}
	}
}

func TestEntryFileName(t *testing.T) {
	got := entryFileName("routes/dashboard")
	if got != "dashboard.entry.tsx" {
		t.Errorf("entryFileName = %q, want %q", got, "dashboard.entry.tsx")
	}
}

func TestBundlePath(t *testing.T) {
	tests := []struct {
		routeDir string
		want     string
	}{
		{"routes/dashboard", "/.rstf/static/dashboard/bundle.js"},
		{"routes/users.$id.edit", "/.rstf/static/users-id-edit/bundle.js"},
	}
	for _, tt := range tests {
		got := bundlePath(tt.routeDir)
		if got != tt.want {
			t.Errorf("bundlePath(%q) = %q, want %q", tt.routeDir, got, tt.want)
		}
	}
}
