package codegen

import (
	"fmt"
	"path/filepath"
	"strings"
)

// GenerateHydrationEntry produces the content of a hydration entry file
// (.rstf/entries/{name}.entry.tsx) for a route directory.
//
// routeDir is the route directory relative to project root (e.g. "routes/dashboard").
// allDeps is the list of all dependency directories that have .go files for this
// route (e.g. ["routes/dashboard", "shared/ui/user-avatar"]). The layout (".")
// is NOT expected in allDeps — it is always included.
//
// The entry file is generated inside .rstf/entries/, so relative imports use
// "../../" to reach the project root.
func GenerateHydrationEntry(routeDir string, allDeps []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")
	b.WriteString("import { hydrateRoot } from \"react-dom/client\";\n")
	b.WriteString("import { View as Layout } from \"../../main\";\n")
	fmt.Fprintf(&b, "import { View as Route } from \"../../%s\";\n", routeDir)

	// Import all generated runtime modules so they initialize _data from
	// window.__RSTF_SERVER_DATA__ at import time.
	b.WriteString("import \"@rstf/main\";\n")
	for _, dep := range allDeps {
		fmt.Fprintf(&b, "import \"@rstf/%s\";\n", dep)
	}

	b.WriteString("hydrateRoot(document, <Layout><Route /></Layout>);\n")
	return b.String()
}

// entryName returns the entry file basename for a route directory.
//
//	"routes/dashboard"       → "dashboard"
//	"routes/index"           → "index"
//	"routes/users.$id.edit"  → "users-id-edit"
func entryName(routeDir string) string {
	name := strings.TrimPrefix(routeDir, "routes/")
	name = strings.ReplaceAll(name, "$", "")
	name = strings.ReplaceAll(name, ".", "-")
	name = strings.ReplaceAll(name, "/", "-")
	return name
}

// entryFileName returns the full filename for an entry file.
//
//	"routes/dashboard" → "dashboard.entry.tsx"
func entryFileName(routeDir string) string {
	return entryName(routeDir) + ".entry.tsx"
}

// bundlePath returns the URL path for a route's client bundle.
//
//	"routes/dashboard" → "/.rstf/static/dashboard/bundle.js"
func bundlePath(routeDir string) string {
	return filepath.ToSlash(filepath.Join("/.rstf/static", entryName(routeDir), "bundle.js"))
}
