package codegen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/rafbgarcia/rstf/internal/conventions"
)

// RouteDef describes a generated route contract shared by the TypeScript and Go
// routing helpers.
type RouteDef struct {
	Dir     string
	Name    string
	Pattern string
	Params  []RouteParamDef
}

// RouteParamDef describes a single path parameter in a route.
type RouteParamDef struct {
	Name    string
	GoField string
}

// BuildRouteDefs returns the sorted route contract generated from the file-based
// route tree.
func BuildRouteDefs(files []RouteFile, deps map[string][]string) []RouteDef {
	seen := map[string]bool{}
	var routeDefs []RouteDef

	addRoute := func(dir string) {
		if !conventions.IsRouteDir(dir) || seen[dir] {
			return
		}
		seen[dir] = true

		name := routeNameForDir(dir)
		routeDefs = append(routeDefs, RouteDef{
			Dir:     dir,
			Name:    name,
			Pattern: conventions.FolderToURLPattern(name),
			Params:  routeParamsForName(name),
		})
	}

	for _, rf := range files {
		addRoute(rf.Dir)
	}
	for dir := range deps {
		addRoute(dir)
	}

	sort.Slice(routeDefs, func(i, j int) bool {
		return routeDefs[i].Name < routeDefs[j].Name
	})
	return routeDefs
}

// GenerateRoutesTS generates the @rstf/routes module.
func GenerateRoutesTS(routeDefs []RouteDef) string {
	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")

	if len(routeDefs) == 0 {
		b.WriteString("export const routes = {} as const;\n\n")
		b.WriteString("export type RouteName = never;\n")
		return b.String()
	}

	b.WriteString("export const routes = {\n")
	for _, route := range routeDefs {
		fmt.Fprintf(&b, "  %q: {\n", route.Name)
		fmt.Fprintf(&b, "    name: %q,\n", route.Name)
		fmt.Fprintf(&b, "    pattern: %q,\n", route.Pattern)
		if len(route.Params) == 0 {
			b.WriteString("    url(): string {\n")
			fmt.Fprintf(&b, "      return %q;\n", routeTemplate(route.Name))
			b.WriteString("    },\n")
		} else {
			b.WriteString("    url(params: { ")
			for i, param := range route.Params {
				if i > 0 {
					b.WriteString("; ")
				}
				fmt.Fprintf(&b, "%s: string", tsPropertyName(param.Name))
			}
			b.WriteString(" }): string {\n")
			fmt.Fprintf(&b, "      return %s;\n", tsLocationExpr(route))
			b.WriteString("    },\n")
		}
		b.WriteString("  },\n")
	}
	b.WriteString("} as const;\n\n")
	b.WriteString("export type RouteName = keyof typeof routes;\n")
	return b.String()
}

// GenerateRoutesGo generates the typed Go routes package.
func GenerateRoutesGo(routeDefs []RouteDef) string {
	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")
	b.WriteString("package routes\n\n")
	if routeDefsHaveParams(routeDefs) {
		b.WriteString("import (\n")
		b.WriteString("\t\"net/url\"\n")
		b.WriteString(")\n\n")
	}
	b.WriteString("type Location string\n\n")
	b.WriteString("func (l Location) URL() string { return string(l) }\n\n")
	b.WriteString("func (l Location) String() string { return string(l) }\n\n")

	for _, route := range routeDefs {
		symbol := routeSymbol(route.Name)
		paramsType := symbol + "Params"
		routeType := symbol + "Route"

		fmt.Fprintf(&b, "type %s struct {\n", paramsType)
		if len(route.Params) == 0 {
			b.WriteString("}\n\n")
		} else {
			for _, param := range route.Params {
				fmt.Fprintf(&b, "\t%s string\n", param.GoField)
			}
			b.WriteString("}\n\n")
		}

		fmt.Fprintf(&b, "type %s struct{}\n\n", routeType)
		fmt.Fprintf(&b, "func (%s) Name() string { return %q }\n\n", routeType, route.Name)
		fmt.Fprintf(&b, "func (%s) Pattern() string { return %q }\n\n", routeType, route.Pattern)

		if len(route.Params) == 0 {
			fmt.Fprintf(&b, "func (%s) URL() Location {\n", routeType)
			fmt.Fprintf(&b, "\treturn %s\n", goLocationExpr(route))
			b.WriteString("}\n\n")
		} else {
			fmt.Fprintf(&b, "func (%s) URL(params %s) Location {\n", routeType, paramsType)
			fmt.Fprintf(&b, "\treturn %s\n", goLocationExpr(route))
			b.WriteString("}\n\n")
		}

		fmt.Fprintf(&b, "var %s %s\n\n", symbol, routeType)
	}

	return b.String()
}

func routeDefsHaveParams(routeDefs []RouteDef) bool {
	for _, route := range routeDefs {
		if len(route.Params) > 0 {
			return true
		}
	}
	return false
}

func routeNameForDir(dir string) string {
	return strings.TrimPrefix(dir, "routes/")
}

func routeTemplate(routeName string) string {
	if routeName == "index" {
		return "/"
	}

	segments := strings.Split(routeName, ".")
	return "/" + strings.Join(segments, "/")
}

func routeParamsForName(routeName string) []RouteParamDef {
	if routeName == "index" {
		return nil
	}

	var params []RouteParamDef
	for _, seg := range strings.Split(routeName, ".") {
		if !strings.HasPrefix(seg, "$") {
			continue
		}
		name := strings.TrimPrefix(seg, "$")
		params = append(params, RouteParamDef{
			Name:    name,
			GoField: goExportedName(name),
		})
	}
	return params
}

func routeSymbol(routeName string) string {
	if routeName == "index" {
		return "Index"
	}

	var b strings.Builder
	for i, seg := range strings.Split(routeName, ".") {
		if i > 0 {
			b.WriteString("Dot")
		}
		b.WriteString(goExportedName(strings.TrimPrefix(seg, "$")))
	}
	return b.String()
}

func goExportedName(raw string) string {
	var b strings.Builder
	parts := strings.FieldsFunc(raw, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	if len(parts) == 0 {
		return "Value"
	}
	for _, part := range parts {
		if part == "" {
			continue
		}
		b.WriteString(ucFirst(part))
	}
	name := b.String()
	if name == "" {
		return "Value"
	}
	if unicode.IsDigit(rune(name[0])) {
		return "P" + name
	}
	return name
}

func tsPropertyName(name string) string {
	if isTSIdentifier(name) {
		return name
	}
	return strconv.Quote(name)
}

func isTSIdentifier(name string) bool {
	if name == "" {
		return false
	}
	for i, r := range name {
		if i == 0 {
			if !(r == '_' || r == '$' || unicode.IsLetter(r)) {
				return false
			}
			continue
		}
		if !(r == '_' || r == '$' || unicode.IsLetter(r) || unicode.IsDigit(r)) {
			return false
		}
	}
	return true
}

func goLocationExpr(route RouteDef) string {
	if route.Name == "index" {
		return `Location("/")`
	}

	var exprs []string
	var static strings.Builder
	appendStatic := func() {
		if static.Len() == 0 {
			return
		}
		exprs = append(exprs, strconv.Quote(static.String()))
		static.Reset()
	}

	for _, seg := range strings.Split(route.Name, ".") {
		static.WriteString("/")
		if strings.HasPrefix(seg, "$") {
			appendStatic()
			exprs = append(exprs, "url.PathEscape(params."+goExportedName(strings.TrimPrefix(seg, "$"))+")")
			continue
		}
		static.WriteString(seg)
	}
	appendStatic()

	return "Location(" + strings.Join(exprs, " + ") + ")"
}

func tsLocationExpr(route RouteDef) string {
	if route.Name == "index" {
		return `"/"`
	}

	var exprs []string
	var static strings.Builder
	appendStatic := func() {
		if static.Len() == 0 {
			return
		}
		exprs = append(exprs, strconv.Quote(static.String()))
		static.Reset()
	}

	for _, seg := range strings.Split(route.Name, ".") {
		static.WriteString("/")
		if strings.HasPrefix(seg, "$") {
			appendStatic()
			exprs = append(exprs, "encodeURIComponent(params."+tsPropertyAccess(strings.TrimPrefix(seg, "$"))+")")
			continue
		}
		static.WriteString(seg)
	}
	appendStatic()

	return strings.Join(exprs, " + ")
}

func tsPropertyAccess(name string) string {
	if isTSIdentifier(name) {
		return name
	}
	return "[" + strconv.Quote(name) + "]"
}
