package codegen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/rafbgarcia/rstf/internal/conventions"
)

// RouteDef describes a generated route contract shared by the TypeScript and Go
// routing helpers.
type RouteDef struct {
	Dir      string
	Name     string
	Pattern  string
	Params   []RouteParamDef
	RPCFuncs []RPCFuncDef
}

// RouteParamDef describes a single path parameter in a route.
type RouteParamDef struct {
	Name    string
	GoField string
}

// RPCFuncDef describes a generated query, mutation, or action contract.
type RPCFuncDef struct {
	Name          string
	Kind          RouteFuncKind
	InputType     string
	InputIsSlice  bool
	ReturnType    string
	ReturnIsSlice bool
}

// BuildRouteDefs returns the sorted route contract generated from the file-based
// route tree.
func BuildRouteDefs(files []RouteFile, deps map[string][]string) []RouteDef {
	fileMap := map[string]RouteFile{}
	for _, rf := range files {
		fileMap[rf.Dir] = rf
	}

	seen := map[string]bool{}
	var routeDefs []RouteDef

	addRoute := func(dir string) {
		if !conventions.IsRouteDir(dir) || seen[dir] {
			return
		}
		seen[dir] = true

		name := routeNameForDir(dir)
		rpcFuncs := routeRPCFuncs(fileMap[dir])
		routeDefs = append(routeDefs, RouteDef{
			Dir:      dir,
			Name:     name,
			Pattern:  conventions.FolderToURLPattern(name),
			Params:   routeParamsForName(name),
			RPCFuncs: rpcFuncs,
		})
	}

	for _, rf := range files {
		addRoute(rf.Dir)
	}
	for dir := range deps {
		addRoute(dir)
	}

	sort.Slice(routeDefs, func(i, j int) bool {
		return routeDefs[i].Name < routeDefs[j].Name
	})
	return routeDefs
}

// GenerateRoutesTS generates the @rstf/routes module.
func GenerateRoutesTS(routeDefs []RouteDef) string {
	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")
	b.WriteString("import { defineAction, defineMutation, defineQuery, useAction, useMutation, useQuery } from \"./client\";\n\n")

	if len(routeDefs) == 0 {
		b.WriteString("export const routes = {} as const;\n\n")
		b.WriteString("export { useAction, useMutation, useQuery };\n")
		b.WriteString("export type RouteName = never;\n")
		return b.String()
	}

	b.WriteString("export const routes = {\n")
	for _, route := range routeDefs {
		fmt.Fprintf(&b, "  %q: {\n", route.Name)
		fmt.Fprintf(&b, "    pattern: %q,\n", route.Pattern)
		if len(route.Params) == 0 {
			b.WriteString("    url(): string {\n")
			fmt.Fprintf(&b, "      return %q;\n", routeTemplate(route.Name))
			b.WriteString("    },\n")
		} else {
			b.WriteString("    url(params: { ")
			for i, param := range route.Params {
				if i > 0 {
					b.WriteString("; ")
				}
				fmt.Fprintf(&b, "%s: string", tsPropertyName(param.Name))
			}
			b.WriteString(" }): string {\n")
			fmt.Fprintf(&b, "      return %s;\n", tsLocationExpr(route))
			b.WriteString("    },\n")
		}
		for _, fn := range route.RPCFuncs {
			switch fn.Kind {
			case RouteFuncKindQuery:
				fmt.Fprintf(
					&b,
					"    %s: defineQuery<%s, %s>(%q, %q),\n",
					fn.Name,
					tsParamsType(route),
					tsRPCType(route.Dir, fn.ReturnType, fn.ReturnIsSlice, true),
					route.Name,
					fn.Name,
				)
			case RouteFuncKindMutation:
				fmt.Fprintf(
					&b,
					"    %s: defineMutation<%s, %s, %s>(%q, %q),\n",
					fn.Name,
					tsParamsType(route),
					tsRPCInputType(route.Dir, fn),
					tsRPCType(route.Dir, fn.ReturnType, fn.ReturnIsSlice, false),
					route.Name,
					fn.Name,
				)
			case RouteFuncKindAction:
				fmt.Fprintf(
					&b,
					"    %s: defineAction<%s, %s, %s>(%q, %q),\n",
					fn.Name,
					tsParamsType(route),
					tsRPCInputType(route.Dir, fn),
					tsRPCType(route.Dir, fn.ReturnType, fn.ReturnIsSlice, false),
					route.Name,
					fn.Name,
				)
			}
		}
		b.WriteString("  },\n")
	}
	b.WriteString("} as const;\n\n")
	b.WriteString("export { useAction, useMutation, useQuery };\n")
	b.WriteString("export type RouteName = keyof typeof routes;\n")
	return b.String()
}

// GenerateRoutesGo generates the typed Go routes package.
func GenerateRoutesGo(routeDefs []RouteDef) string {
	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")
	b.WriteString("package routes\n\n")
	hasParams := routeDefsHaveParams(routeDefs)
	hasQueries := routeDefsHaveQueries(routeDefs)
	if hasParams || hasQueries {
		b.WriteString("import (\n")
		if hasParams {
			b.WriteString("\t\"net/url\"\n")
		}
		if hasQueries {
			fmt.Fprintf(&b, "\trstf %q\n", frameworkModule)
		}
		b.WriteString(")\n\n")
	}
	b.WriteString("type Location string\n\n")
	b.WriteString("func (l Location) URL() string { return string(l) }\n\n")
	b.WriteString("func (l Location) String() string { return string(l) }\n\n")
	if hasQueries {
		b.WriteString("type QueryKey[P any] struct {\n")
		b.WriteString("\tbuild func(P) rstf.SubscriptionKey\n")
		b.WriteString("}\n\n")
		b.WriteString("func (q QueryKey[P]) Key(params P) rstf.SubscriptionKey {\n")
		b.WriteString("\treturn q.build(params)\n")
		b.WriteString("}\n\n")
		b.WriteString("func (q QueryKey[P]) Invalidate(ctx *rstf.MutationContext, params P) {\n")
		b.WriteString("\tif ctx == nil {\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
		b.WriteString("\tctx.Invalidate(q.Key(params))\n")
		b.WriteString("}\n\n")
	}

	for _, route := range routeDefs {
		symbol := routeSymbol(route.Name)
		paramsType := symbol + "Params"
		routeType := symbol + "Route"

		fmt.Fprintf(&b, "type %s struct {\n", paramsType)
		if len(route.Params) == 0 {
			b.WriteString("}\n\n")
		} else {
			for _, param := range route.Params {
				fmt.Fprintf(&b, "\t%s string\n", param.GoField)
			}
			b.WriteString("}\n\n")
		}

		fmt.Fprintf(&b, "type %s struct{}\n\n", routeType)
		fmt.Fprintf(&b, "func (%s) Name() string { return %q }\n\n", routeType, route.Name)
		fmt.Fprintf(&b, "func (%s) Pattern() string { return %q }\n\n", routeType, route.Pattern)

		if len(route.Params) == 0 {
			fmt.Fprintf(&b, "func (%s) URL() Location {\n", routeType)
			fmt.Fprintf(&b, "\treturn %s\n", goLocationExpr(route))
			b.WriteString("}\n\n")
		} else {
			fmt.Fprintf(&b, "func (%s) URL(params %s) Location {\n", routeType, paramsType)
			fmt.Fprintf(&b, "\treturn %s\n", goLocationExpr(route))
			b.WriteString("}\n\n")
		}

		fmt.Fprintf(&b, "var %s %s\n\n", symbol, routeType)

		for _, fn := range route.RPCFuncs {
			if fn.Kind != RouteFuncKindQuery {
				continue
			}
			fmt.Fprintf(&b, "var %s%s = QueryKey[%s]{\n", symbol, fn.Name, paramsType)
			fmt.Fprintf(&b, "\tbuild: func(params %s) rstf.SubscriptionKey {\n", paramsType)
			fmt.Fprintf(
				&b,
				"\t\treturn rstf.NewSubscriptionKey(%q, %q, %s)\n",
				route.Name,
				fn.Name,
				goParamsMapExpr(route),
			)
			b.WriteString("\t},\n")
			b.WriteString("}\n\n")
		}
	}

	return b.String()
}

func routeDefsHaveParams(routeDefs []RouteDef) bool {
	for _, route := range routeDefs {
		if len(route.Params) > 0 {
			return true
		}
	}
	return false
}

func routeDefsHaveQueries(routeDefs []RouteDef) bool {
	for _, route := range routeDefs {
		for _, fn := range route.RPCFuncs {
			if fn.Kind == RouteFuncKindQuery {
				return true
			}
		}
	}
	return false
}

func routeNameForDir(dir string) string {
	return strings.TrimPrefix(dir, "routes/")
}

func routeRPCFuncs(rf RouteFile) []RPCFuncDef {
	var funcs []RPCFuncDef
	for _, fn := range rf.Funcs {
		switch fn.Kind {
		case RouteFuncKindQuery, RouteFuncKindMutation, RouteFuncKindAction:
			funcs = append(funcs, RPCFuncDef{
				Name:          fn.Name,
				Kind:          fn.Kind,
				InputType:     fn.InputType,
				InputIsSlice:  fn.InputIsSlice,
				ReturnType:    fn.ReturnType,
				ReturnIsSlice: fn.ReturnIsSlice,
			})
		}
	}
	sort.Slice(funcs, func(i, j int) bool {
		if funcs[i].Kind != funcs[j].Kind {
			return funcs[i].Kind < funcs[j].Kind
		}
		return funcs[i].Name < funcs[j].Name
	})
	return funcs
}

func routeTemplate(routeName string) string {
	if routeName == "index" {
		return "/"
	}

	segments := strings.Split(routeName, ".")
	for i, seg := range segments {
		if isDynamicRouteSegment(seg) {
			segments[i] = "{" + seg[1:] + "}"
		}
	}
	return "/" + strings.Join(segments, "/")
}

func routeParamsForName(routeName string) []RouteParamDef {
	if routeName == "index" {
		return nil
	}

	var params []RouteParamDef
	for _, seg := range strings.Split(routeName, ".") {
		if !isDynamicRouteSegment(seg) {
			continue
		}
		name := strings.TrimPrefix(seg, "_")
		params = append(params, RouteParamDef{
			Name:    name,
			GoField: goExportedName(name),
		})
	}
	return params
}

func routeSymbol(routeName string) string {
	if routeName == "index" {
		return "Index"
	}

	var b strings.Builder
	for i, seg := range strings.Split(routeName, ".") {
		if i > 0 {
			b.WriteString("Dot")
		}
		b.WriteString(goExportedName(strings.TrimPrefix(seg, "_")))
	}
	return b.String()
}

func goExportedName(raw string) string {
	var b strings.Builder
	parts := strings.FieldsFunc(raw, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	if len(parts) == 0 {
		return "Value"
	}
	for _, part := range parts {
		if part == "" {
			continue
		}
		b.WriteString(ucFirst(part))
	}
	name := b.String()
	if name == "" {
		return "Value"
	}
	if unicode.IsDigit(rune(name[0])) {
		return "P" + name
	}
	return name
}

func tsPropertyName(name string) string {
	if isTSIdentifier(name) {
		return name
	}
	return strconv.Quote(name)
}

func isTSIdentifier(name string) bool {
	if name == "" {
		return false
	}
	for i, r := range name {
		if i == 0 {
			if !(r == '_' || r == '$' || unicode.IsLetter(r)) {
				return false
			}
			continue
		}
		if !(r == '_' || r == '$' || unicode.IsLetter(r) || unicode.IsDigit(r)) {
			return false
		}
	}
	return true
}

func goLocationExpr(route RouteDef) string {
	if route.Name == "index" {
		return `Location("/")`
	}

	var exprs []string
	var static strings.Builder
	appendStatic := func() {
		if static.Len() == 0 {
			return
		}
		exprs = append(exprs, strconv.Quote(static.String()))
		static.Reset()
	}

	for _, seg := range strings.Split(route.Name, ".") {
		static.WriteString("/")
		if isDynamicRouteSegment(seg) {
			appendStatic()
			exprs = append(exprs, "url.PathEscape(params."+goExportedName(strings.TrimPrefix(seg, "_"))+")")
			continue
		}
		static.WriteString(seg)
	}
	appendStatic()

	return "Location(" + strings.Join(exprs, " + ") + ")"
}

func tsLocationExpr(route RouteDef) string {
	if route.Name == "index" {
		return `"/"`
	}

	var exprs []string
	var static strings.Builder
	appendStatic := func() {
		if static.Len() == 0 {
			return
		}
		exprs = append(exprs, strconv.Quote(static.String()))
		static.Reset()
	}

	for _, seg := range strings.Split(route.Name, ".") {
		static.WriteString("/")
		if isDynamicRouteSegment(seg) {
			appendStatic()
			exprs = append(exprs, "encodeURIComponent(params."+tsPropertyAccess(strings.TrimPrefix(seg, "_"))+")")
			continue
		}
		static.WriteString(seg)
	}
	appendStatic()

	return strings.Join(exprs, " + ")
}

func tsParamsType(route RouteDef) string {
	if len(route.Params) == 0 {
		return "Record<string, never>"
	}
	var b strings.Builder
	b.WriteString("{ ")
	for i, param := range route.Params {
		if i > 0 {
			b.WriteString("; ")
		}
		fmt.Fprintf(&b, "%s: string", tsPropertyName(param.Name))
	}
	b.WriteString(" }")
	return b.String()
}

func tsRPCInputType(routeDir string, fn RPCFuncDef) string {
	if fn.InputType == "" {
		return "void"
	}
	return tsRPCType(routeDir, fn.InputType, fn.InputIsSlice, false)
}

func tsRPCType(routeDir, typeName string, isSlice bool, allowVoid bool) string {
	if typeName == "" {
		if allowVoid {
			return "never"
		}
		return "void"
	}
	tsType := goTypeToTS(typeName, isSlice)
	if isPrimitiveGoType(typeName) {
		return tsType
	}
	return Namespace(routeDir) + "." + tsType
}

func goParamsMapExpr(route RouteDef) string {
	if len(route.Params) == 0 {
		return "map[string]string{}"
	}
	parts := make([]string, 0, len(route.Params))
	for _, param := range route.Params {
		parts = append(parts, fmt.Sprintf("%q: params.%s", param.Name, param.GoField))
	}
	return "map[string]string{" + strings.Join(parts, ", ") + "}"
}

func tsPropertyAccess(name string) string {
	if isTSIdentifier(name) {
		return name
	}
	return "[" + strconv.Quote(name) + "]"
}

func isDynamicRouteSegment(seg string) bool {
	return len(seg) > 1 && strings.HasPrefix(seg, "_")
}
