package codegen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/rafbgarcia/rstf/internal/conventions"
)

// RouteDef describes a generated route contract shared by the TypeScript and Go
// routing helpers.
type RouteDef struct {
	Dir     string
	Name    string
	Pattern string
	Params  []RouteParamDef
}

// RouteParamDef describes a single path parameter in a route.
type RouteParamDef struct {
	Name    string
	GoField string
}

// BuildRouteDefs returns the sorted route contract generated from the file-based
// route tree.
func BuildRouteDefs(files []RouteFile, deps map[string][]string) []RouteDef {
	seen := map[string]bool{}
	var routeDefs []RouteDef

	addRoute := func(dir string) {
		if !conventions.IsRouteDir(dir) || seen[dir] {
			return
		}
		seen[dir] = true

		name := routeNameForDir(dir)
		routeDefs = append(routeDefs, RouteDef{
			Dir:     dir,
			Name:    name,
			Pattern: conventions.FolderToURLPattern(name),
			Params:  routeParamsForName(name),
		})
	}

	for _, rf := range files {
		addRoute(rf.Dir)
	}
	for dir := range deps {
		addRoute(dir)
	}

	sort.Slice(routeDefs, func(i, j int) bool {
		return routeDefs[i].Name < routeDefs[j].Name
	})
	return routeDefs
}

// GenerateRoutesTS generates the @rstf/routes module.
func GenerateRoutesTS(routeDefs []RouteDef) string {
	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")
	b.WriteString("export type RouteParamValue = string | number;\n\n")

	if len(routeDefs) == 0 {
		b.WriteString("export type RouteName = never;\n\n")
		b.WriteString("const routeTable = {} as const;\n\n")
		b.WriteString("export function url(name: never, params?: never): string {\n")
		b.WriteString("  throw new Error(`unknown route: ${String(name)}`);\n")
		b.WriteString("}\n\n")
		b.WriteString("export const routes = { url } as const;\n")
		return b.String()
	}

	b.WriteString("export type RouteName =\n")
	for i, route := range routeDefs {
		sep := " |"
		if i == 0 {
			sep = "  "
		}
		fmt.Fprintf(&b, "%s %q\n", sep, route.Name)
	}
	b.WriteString(";\n\n")

	b.WriteString("const routeTable = {\n")
	for _, route := range routeDefs {
		fmt.Fprintf(&b, "  %q: { path: %q, params: [", route.Name, routeTemplate(route.Name))
		for i, param := range route.Params {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", param.Name)
		}
		b.WriteString("] },\n")
	}
	b.WriteString("} as const;\n\n")

	for _, route := range routeDefs {
		if len(route.Params) == 0 {
			fmt.Fprintf(&b, "export function url(name: %q): string;\n", route.Name)
			continue
		}

		fmt.Fprintf(&b, "export function url(name: %q, params: { ", route.Name)
		for i, param := range route.Params {
			if i > 0 {
				b.WriteString("; ")
			}
			fmt.Fprintf(&b, "%s: RouteParamValue", tsPropertyName(param.Name))
		}
		b.WriteString(" }): string;\n")
	}

	b.WriteString("export function url(name: RouteName, params?: Record<string, RouteParamValue>): string {\n")
	b.WriteString("  const route = routeTable[name];\n")
	b.WriteString("  if (!route) {\n")
	b.WriteString("    throw new Error(`unknown route: ${name}`);\n")
	b.WriteString("  }\n")
	b.WriteString("  let path: string = route.path;\n")
	b.WriteString("  for (const paramName of route.params) {\n")
	b.WriteString("    const value = params?.[paramName];\n")
	b.WriteString("    if (value === undefined || value === null) {\n")
	b.WriteString("      throw new Error(`missing route param ${paramName} for ${name}`);\n")
	b.WriteString("    }\n")
	b.WriteString("    path = path.replace(`$${paramName}`, encodeURIComponent(String(value)));\n")
	b.WriteString("  }\n")
	b.WriteString("  return path;\n")
	b.WriteString("}\n\n")

	b.WriteString("export const routes = { url } as const;\n")
	return b.String()
}

// GenerateRoutesGo generates the typed Go routes package.
func GenerateRoutesGo(routeDefs []RouteDef) string {
	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")
	b.WriteString("package routes\n\n")
	if routeDefsHaveParams(routeDefs) {
		b.WriteString("import (\n")
		b.WriteString("\t\"net/url\"\n")
		b.WriteString(")\n\n")
	}
	b.WriteString("type Location string\n\n")
	b.WriteString("func (l Location) URL() string { return string(l) }\n\n")
	b.WriteString("func (l Location) String() string { return string(l) }\n\n")
	b.WriteString("type Route[P any] struct {\n")
	b.WriteString("\tname    string\n")
	b.WriteString("\tpattern string\n")
	b.WriteString("\tbuild   func(P) Location\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r Route[P]) Name() string { return r.name }\n\n")
	b.WriteString("func (r Route[P]) Pattern() string { return r.pattern }\n\n")
	b.WriteString("func URL[P any](route Route[P], params P) Location {\n")
	b.WriteString("\treturn route.build(params)\n")
	b.WriteString("}\n\n")

	for _, route := range routeDefs {
		symbol := routeSymbol(route.Name)
		paramsType := symbol + "Params"

		fmt.Fprintf(&b, "type %s struct {\n", paramsType)
		if len(route.Params) == 0 {
			b.WriteString("}\n\n")
		} else {
			for _, param := range route.Params {
				fmt.Fprintf(&b, "\t%s string\n", param.GoField)
			}
			b.WriteString("}\n\n")
		}

		fmt.Fprintf(&b, "var %s = Route[%s]{\n", symbol, paramsType)
		fmt.Fprintf(&b, "\tname: %q,\n", route.Name)
		fmt.Fprintf(&b, "\tpattern: %q,\n", route.Pattern)
		fmt.Fprintf(&b, "\tbuild: func(params %s) Location {\n", paramsType)
		fmt.Fprintf(&b, "\t\treturn %s\n", goLocationExpr(route))
		b.WriteString("\t},\n")
		b.WriteString("}\n\n")

		if len(route.Params) == 0 {
			fmt.Fprintf(&b, "func %sURL() Location {\n", symbol)
			fmt.Fprintf(&b, "\treturn URL(%s, %s{})\n", symbol, paramsType)
			b.WriteString("}\n\n")
			continue
		}

		fmt.Fprintf(&b, "func %sURL(params %s) Location {\n", symbol, paramsType)
		fmt.Fprintf(&b, "\treturn URL(%s, params)\n", symbol)
		b.WriteString("}\n\n")
	}

	return b.String()
}

func routeDefsHaveParams(routeDefs []RouteDef) bool {
	for _, route := range routeDefs {
		if len(route.Params) > 0 {
			return true
		}
	}
	return false
}

func routeNameForDir(dir string) string {
	return strings.TrimPrefix(dir, "routes/")
}

func routeTemplate(routeName string) string {
	if routeName == "index" {
		return "/"
	}

	segments := strings.Split(routeName, ".")
	return "/" + strings.Join(segments, "/")
}

func routeParamsForName(routeName string) []RouteParamDef {
	if routeName == "index" {
		return nil
	}

	var params []RouteParamDef
	for _, seg := range strings.Split(routeName, ".") {
		if !strings.HasPrefix(seg, "$") {
			continue
		}
		name := strings.TrimPrefix(seg, "$")
		params = append(params, RouteParamDef{
			Name:    name,
			GoField: goExportedName(name),
		})
	}
	return params
}

func routeSymbol(routeName string) string {
	if routeName == "index" {
		return "Index"
	}

	var b strings.Builder
	for _, seg := range strings.Split(routeName, ".") {
		if strings.HasPrefix(seg, "$") {
			b.WriteString("Param")
			b.WriteString(goExportedName(strings.TrimPrefix(seg, "$")))
			continue
		}
		b.WriteString(goExportedName(seg))
	}
	return b.String()
}

func goExportedName(raw string) string {
	var b strings.Builder
	parts := strings.FieldsFunc(raw, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	if len(parts) == 0 {
		return "Value"
	}
	for _, part := range parts {
		if part == "" {
			continue
		}
		b.WriteString(ucFirst(part))
	}
	name := b.String()
	if name == "" {
		return "Value"
	}
	if unicode.IsDigit(rune(name[0])) {
		return "P" + name
	}
	return name
}

func tsPropertyName(name string) string {
	if isTSIdentifier(name) {
		return name
	}
	return strconv.Quote(name)
}

func isTSIdentifier(name string) bool {
	if name == "" {
		return false
	}
	for i, r := range name {
		if i == 0 {
			if !(r == '_' || r == '$' || unicode.IsLetter(r)) {
				return false
			}
			continue
		}
		if !(r == '_' || r == '$' || unicode.IsLetter(r) || unicode.IsDigit(r)) {
			return false
		}
	}
	return true
}

func goLocationExpr(route RouteDef) string {
	if route.Name == "index" {
		return `Location("/")`
	}

	var exprs []string
	var static strings.Builder
	appendStatic := func() {
		if static.Len() == 0 {
			return
		}
		exprs = append(exprs, strconv.Quote(static.String()))
		static.Reset()
	}

	for _, seg := range strings.Split(route.Name, ".") {
		static.WriteString("/")
		if strings.HasPrefix(seg, "$") {
			appendStatic()
			exprs = append(exprs, "url.PathEscape(params."+goExportedName(strings.TrimPrefix(seg, "$"))+")")
			continue
		}
		static.WriteString(seg)
	}
	appendStatic()

	return "Location(" + strings.Join(exprs, " + ") + ")"
}
