package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/rafbgarcia/rstf/internal/conventions"
)

// frameworkModule is the import path of the rstf framework itself.
const frameworkModule = "github.com/rafbgarcia/rstf"

// serverImport tracks a user-package import for the generated server file.
type serverImport struct {
	Alias      string // Go import alias (e.g. "app", "dashboard")
	ImportPath string // full import path
	Dir        string // project-relative dir (e.g. ".", "routes/dashboard")
	HasContext bool   // whether SSR() takes *rstf.Context
	HasSSR     bool   // whether the package exports SSR.
}

// routeEntry pairs a route directory with its computed URL pattern and handlers.
type routeEntry struct {
	dir           string
	urlPattern    string
	hasComponent  bool
	hasSSR        bool
	hasGET        bool
	hasPOST       bool
	hasPUT        bool
	hasPATCH      bool
	hasDELETE     bool
	ssrHasContext bool
	rpcFuncs      []RouteFunc
}

// GenerateServer produces the content of .rstf/server_gen.go — the Go entry
// point that wires routes to handlers, calls route functions, and renders via
// the Node sidecar.
func GenerateServer(modulePath string, files []RouteFile, deps map[string][]string) (string, error) {
	fileMap := map[string]RouteFile{}
	for _, f := range files {
		fileMap[f.Dir] = f
	}

	layout, hasLayout := fileMap["."]

	if hasLayout && layout.Package == "main" {
		return "", fmt.Errorf(
			"main.go: package main is reserved for rstf, please use a different package name (e.g. your app name)",
		)
	}

	routeMap := map[string]routeEntry{}
	for _, f := range files {
		if !conventions.IsRouteDir(f.Dir) {
			continue
		}
		folder := strings.TrimPrefix(f.Dir, "routes/")
		e := routeEntry{
			dir:        f.Dir,
			urlPattern: conventions.FolderToURLPattern(folder),
		}
		for _, fn := range f.Funcs {
			switch fn.Name {
			case "SSR":
				e.hasSSR = true
				e.ssrHasContext = fn.HasContext
			case "GET":
				e.hasGET = true
			case "POST":
				e.hasPOST = true
			case "PUT":
				e.hasPUT = true
			case "PATCH":
				e.hasPATCH = true
			case "DELETE":
				e.hasDELETE = true
			}
			switch fn.Kind {
			case RouteFuncKindQuery, RouteFuncKindMutation, RouteFuncKindAction:
				e.rpcFuncs = append(e.rpcFuncs, fn)
			}
		}
		routeMap[f.Dir] = e
	}

	for routeDir := range deps {
		if !conventions.IsRouteDir(routeDir) {
			continue
		}
		e := routeMap[routeDir]
		if e.dir == "" {
			folder := strings.TrimPrefix(routeDir, "routes/")
			e = routeEntry{dir: routeDir, urlPattern: conventions.FolderToURLPattern(folder)}
		}
		e.hasComponent = true
		routeMap[routeDir] = e
	}

	var routes []routeEntry
	for _, e := range routeMap {
		routes = append(routes, e)
	}
	sort.Slice(routes, func(i, j int) bool {
		return routes[i].urlPattern < routes[j].urlPattern
	})

	imports := collectImports(modulePath, layout, hasLayout, routes, deps, fileMap)

	aliasMap := map[string]serverImport{}
	for _, imp := range imports {
		aliasMap[imp.Dir] = imp
	}

	var b strings.Builder
	writeHeader(&b)
	writeImports(&b, imports)
	writeAcceptHelpers(&b)
	writeStructToMap(&b)
	writeAssemblePage(&b)
	writeRequestHelpers(&b)
	writeRPCHelpers(&b)
	writeRPCDispatchers(&b, routes, aliasMap)
	writeResponseHelpers(&b)
	writeMain(&b, routes, layout, hasLayout, aliasMap, deps)
	return b.String(), nil
}

// collectImports gathers all unique user-package imports across the layout and
// all routes, assigning collision-free aliases.
func collectImports(
	modulePath string,
	layout RouteFile,
	hasLayout bool,
	routes []routeEntry,
	deps map[string][]string,
	fileMap map[string]RouteFile,
) []serverImport {
	seen := map[string]bool{}
	usedAliases := map[string]int{}
	var imports []serverImport

	addImport := func(dir string) {
		if seen[dir] {
			return
		}
		seen[dir] = true

		rf, ok := fileMap[dir]
		if !ok {
			return
		}

		var importPath string
		var baseAlias string
		if dir == "." {
			importPath = modulePath
			baseAlias = "app"
		} else if strings.Contains(dir, "$") {
			importPath = modulePath + "/.rstf/pkgs/" + strings.ReplaceAll(dir, "$", "")
			baseAlias = rf.Package
		} else {
			importPath = modulePath + "/" + dir
			baseAlias = rf.Package
		}

		alias := baseAlias
		if count, exists := usedAliases[baseAlias]; exists {
			alias = fmt.Sprintf("%s%d", baseAlias, count+1)
		}
		usedAliases[baseAlias]++

		hasCtx := false
		hasSSR := false
		for _, fn := range rf.Funcs {
			if fn.Name == "SSR" {
				hasSSR = true
				hasCtx = fn.HasContext
				break
			}
		}

		imports = append(imports, serverImport{
			Alias:      alias,
			ImportPath: importPath,
			Dir:        dir,
			HasContext: hasCtx,
			HasSSR:     hasSSR,
		})
	}

	if hasLayout {
		addImport(".")
	}

	for _, r := range routes {
		addImport(r.dir)
		for _, depDir := range deps[r.dir] {
			addImport(depDir)
		}
	}

	return imports
}

func writeHeader(b *strings.Builder) {
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
}

func writeImports(b *strings.Builder, imports []serverImport) {
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"flag\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"io\"\n")
	b.WriteString("\t\"mime\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"os/signal\"\n")
	b.WriteString("\t\"strconv\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString("\t\"syscall\"\n")
	b.WriteString("\n")
	fmt.Fprintf(b, "\trstf %q\n", frameworkModule)
	fmt.Fprintf(b, "\t%q\n", frameworkModule+"/renderer")
	fmt.Fprintf(b, "\t%q\n", frameworkModule+"/router")
	b.WriteString("\n")
	for _, imp := range imports {
		fmt.Fprintf(b, "\t%s %q\n", imp.Alias, imp.ImportPath)
	}
	b.WriteString(")\n\n")
}

func writeAcceptHelpers(b *strings.Builder) {
	b.WriteString(`func prefersHTML(accept string) bool {
	accept = strings.TrimSpace(accept)
	if accept == "" {
		return true
	}

	hasAny := false
	hasWildcard := false
	parts := strings.Split(accept, ",")
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		mediaType, params, err := mime.ParseMediaType(part)
		if err != nil {
			continue
		}
		q := 1.0
		if qRaw, ok := params["q"]; ok {
			if parsed, err := strconv.ParseFloat(qRaw, 64); err == nil {
				q = parsed
			}
		}
		if q <= 0 {
			continue
		}
		hasAny = true

		mediaType = strings.ToLower(strings.TrimSpace(mediaType))
		if mediaType == "text/html" || mediaType == "application/xhtml+xml" {
			return true
		}
		if mediaType == "*/*" {
			hasWildcard = true
		}
	}

	if !hasAny {
		return true
	}
	return hasWildcard
}

func allowHeader(methods []string) string {
	return strings.Join(methods, ", ")
}

func methodNotAllowed(w http.ResponseWriter, methods []string) {
	w.Header().Set("Allow", allowHeader(methods))
	w.WriteHeader(http.StatusMethodNotAllowed)
}
`)
	b.WriteString("\n")
}

func writeStructToMap(b *strings.Builder) {
	b.WriteString(`func structToMap(v any) map[string]any {
	b, err := json.Marshal(v)
	if err != nil {
		return map[string]any{}
	}
	var m map[string]any
	if err := json.Unmarshal(b, &m); err != nil {
		return map[string]any{}
	}
	if m == nil {
		return map[string]any{}
	}
	return m
}`)
	b.WriteString("\n\n")
}

func writeAssemblePage(b *strings.Builder) {
	b.WriteString(`func assemblePage(html string, serverData map[string]map[string]any, bundlePath string, cssPath string) string {
	sdJSON, err := json.Marshal(serverData)
	if err != nil {
		sdJSON = []byte("{}")
	}
	dataScript := "<script>window.__RSTF_SERVER_DATA__ = " + string(sdJSON) + "</script>"
	bundleScript := "<script src=\"" + bundlePath + "\"></script>"
	page := "<!DOCTYPE html>" + html
	if cssPath != "" {
		page = strings.Replace(page, "</head>", "<link rel=\"stylesheet\" href=\""+cssPath+"\">\n</head>", 1)
	}
	page = strings.Replace(page, "</body>", dataScript+bundleScript+"</body>", 1)
	return page
}`)
	b.WriteString("\n\n")
}

func writeRequestHelpers(b *strings.Builder) {
	b.WriteString(`func newRequestContext(req *http.Request, rstfApp *rstf.App) (*rstf.Context, error) {
	ctx := rstf.NewContext(req)
	ctx.DB = rstfApp.DB()
	if err := ctx.SetRequestBodyLimitBytes(rstfApp.RequestBodyLimitBytes()); err != nil {
		return nil, err
	}
	return ctx, nil
}

func invokeRouteAction(
	w http.ResponseWriter,
	req *http.Request,
	rstfApp *rstf.App,
	head bool,
	action func(*rstf.Context) error,
) {
	tracker := rstf.NewResponseTracker(w)
	ctx, err := newRequestContext(req, rstfApp)
	if err != nil {
		if !tracker.Written() {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
		return
	}
	if head {
		ctx.Writer = rstf.NewHeadWriter(tracker)
	} else {
		ctx.Writer = tracker
	}
	if err := action(ctx); err != nil {
		if !tracker.Written() {
			rstf.WriteErrorEnvelope(tracker, err)
		}
		return
	}
	if !tracker.Written() {
		tracker.WriteHeader(http.StatusNoContent)
	}
}
`)
	b.WriteString("\n")
}

func writeRPCHelpers(b *strings.Builder) {
	b.WriteString(`type rpcRequest struct {
	Kind   string          ` + "`json:\"kind\"`" + `
	Route  string          ` + "`json:\"route\"`" + `
	Name   string          ` + "`json:\"name\"`" + `
	Params map[string]string ` + "`json:\"params\"`" + `
	Input  json.RawMessage ` + "`json:\"input\"`" + `
}

type liveSubscribeRequest struct {
	ClientID       string            ` + "`json:\"clientId\"`" + `
	SubscriptionID string            ` + "`json:\"subscriptionId\"`" + `
	Route          string            ` + "`json:\"route\"`" + `
	Name           string            ` + "`json:\"name\"`" + `
	Params         map[string]string ` + "`json:\"params\"`" + `
}

type liveUnsubscribeRequest struct {
	ClientID       string ` + "`json:\"clientId\"`" + `
	SubscriptionID string ` + "`json:\"subscriptionId\"`" + `
}

func decodeJSONBody(req *http.Request, target any) error {
	body, err := io.ReadAll(req.Body)
	if err != nil {
		return err
	}
	if len(body) == 0 {
		return &rstf.RequestError{
			Code:    rstf.ErrorCodeInvalidPayload,
			Message: "request body must not be empty",
			Status:  http.StatusBadRequest,
		}
	}
	if err := json.Unmarshal(body, target); err != nil {
		return &rstf.RequestError{
			Code:    rstf.ErrorCodeInvalidPayload,
			Message: "request body must contain valid JSON",
			Status:  http.StatusBadRequest,
		}
	}
	return nil
}

func cloneRequestWithParams(req *http.Request, params map[string]string) *http.Request {
	cloned := req.Clone(context.Background())
	cloned.Body = http.NoBody
	for key, value := range params {
		cloned.SetPathValue(key, value)
	}
	return cloned
}

func writeRPCSuccess(w http.ResponseWriter, payload any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(map[string]any{"data": payload})
}

func writeSSE(w http.ResponseWriter, event rstf.LiveEvent) error {
	payload, err := json.Marshal(event)
	if err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "data: %s\n\n", payload); err != nil {
		return err
	}
	if flusher, ok := w.(http.Flusher); ok {
		flusher.Flush()
	}
	return nil
}
`)
	b.WriteString("\n")
}

func writeResponseHelpers(b *strings.Builder) {
	b.WriteString(`func writeOptions(w http.ResponseWriter, methods []string) {
	w.Header().Set("Allow", allowHeader(methods))
	w.WriteHeader(http.StatusNoContent)
}

func writeNotAcceptable(w http.ResponseWriter) {
	w.WriteHeader(http.StatusNotAcceptable)
}

func writeHTMLResponse(w http.ResponseWriter, page string, head bool) {
	if head {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Header().Set("Content-Length", strconv.Itoa(len(page)))
		w.WriteHeader(http.StatusOK)
		return
	}
	fmt.Fprint(w, page)
}
`)
	b.WriteString("\n")
}

func writeRPCDispatchers(b *strings.Builder, routes []routeEntry, aliasMap map[string]serverImport) {
	writeExecuteQuery(b, routes, aliasMap)
	writeExecuteMutationOrAction(b, routes, aliasMap)
}

func writeExecuteQuery(b *strings.Builder, routes []routeEntry, aliasMap map[string]serverImport) {
	b.WriteString(`func executeQuery(req *http.Request, rstfApp *rstf.App, routeName string, fnName string, params map[string]string) (any, error) {
	switch routeName {
`)
	for _, route := range routes {
		queryFuncs := rpcFuncsByKind(route.rpcFuncs, RouteFuncKindQuery)
		if len(queryFuncs) == 0 {
			continue
		}
		alias := aliasMap[route.dir].Alias
		fmt.Fprintf(b, "\tcase %q:\n", routeNameForDir(route.dir))
		b.WriteString("\t\tswitch fnName {\n")
		for _, fn := range queryFuncs {
			fmt.Fprintf(b, "\t\tcase %q:\n", fn.Name)
			b.WriteString("\t\t\tctx := rstf.NewQueryContext(cloneRequestWithParams(req, params), rstfApp.DB(), rstfApp.RequestBodyLimitBytes())\n")
			if returnsErrorOnly(fn) {
				fmt.Fprintf(b, "\t\t\tif err := %s.%s(ctx); err != nil {\n", alias, fn.Name)
				b.WriteString("\t\t\t\treturn nil, err\n")
				b.WriteString("\t\t\t}\n")
				b.WriteString("\t\t\treturn nil, nil\n")
			} else if returnsDataAndError(fn) {
				fmt.Fprintf(b, "\t\t\treturn %s.%s(ctx)\n", alias, fn.Name)
			} else {
				fmt.Fprintf(b, "\t\t\treturn %s.%s(ctx), nil\n", alias, fn.Name)
			}
		}
		b.WriteString("\t\t}\n")
	}
	b.WriteString(`	}
	return nil, &rstf.RequestError{
		Code:    rstf.ErrorCodeInvalidPayload,
		Message: "unknown query",
		Status:  http.StatusNotFound,
	}
}

`)
}

func writeExecuteMutationOrAction(b *strings.Builder, routes []routeEntry, aliasMap map[string]serverImport) {
	b.WriteString(`func executeMutationOrAction(
	req *http.Request,
	rstfApp *rstf.App,
	routeName string,
	fnName string,
	kind string,
	params map[string]string,
	input json.RawMessage,
	liveHub *rstf.LiveHub,
) (any, error) {
	switch routeName {
`)
	for _, route := range routes {
		rpcFuncs := rpcFuncsByKinds(route.rpcFuncs, RouteFuncKindMutation, RouteFuncKindAction)
		if len(rpcFuncs) == 0 {
			continue
		}
		alias := aliasMap[route.dir].Alias
		fmt.Fprintf(b, "\tcase %q:\n", routeNameForDir(route.dir))
		b.WriteString("\t\tswitch fnName {\n")
		for _, fn := range rpcFuncs {
			fmt.Fprintf(b, "\t\tcase %q:\n", fn.Name)
			fmt.Fprintf(b, "\t\t\tif kind != %q {\n", fn.Kind)
			b.WriteString("\t\t\t\treturn nil, &rstf.RequestError{Code: rstf.ErrorCodeInvalidPayload, Message: \"rpc kind mismatch\", Status: http.StatusBadRequest}\n")
			b.WriteString("\t\t\t}\n")
			if fn.Kind == RouteFuncKindMutation {
				b.WriteString("\t\t\tctx := rstf.NewMutationContext(cloneRequestWithParams(req, params), rstfApp.DB(), rstfApp.RequestBodyLimitBytes(), liveHub.Invalidate)\n")
			} else {
				b.WriteString("\t\t\tctx := rstf.NewActionContext(cloneRequestWithParams(req, params), rstfApp.RequestBodyLimitBytes())\n")
			}
			writeInputDecodeBlock(b, fn, alias)
			switch {
			case returnsErrorOnly(fn):
				fmt.Fprintf(b, "\t\t\tif err := %s.%s(ctx%s); err != nil {\n", alias, fn.Name, callInputSuffix(fn))
				b.WriteString("\t\t\t\treturn nil, err\n")
				b.WriteString("\t\t\t}\n")
				b.WriteString("\t\t\treturn nil, nil\n")
			case returnsDataAndError(fn):
				fmt.Fprintf(b, "\t\t\treturn %s.%s(ctx%s)\n", alias, fn.Name, callInputSuffix(fn))
			default:
				fmt.Fprintf(b, "\t\t\treturn %s.%s(ctx%s), nil\n", alias, fn.Name, callInputSuffix(fn))
			}
		}
		b.WriteString("\t\t}\n")
	}
	b.WriteString(`	}
	return nil, &rstf.RequestError{
		Code:    rstf.ErrorCodeInvalidPayload,
		Message: "unknown rpc function",
		Status:  http.StatusNotFound,
	}
}

`)
}

func writeInputDecodeBlock(b *strings.Builder, fn RouteFunc, alias string) {
	if fn.InputType == "" {
		return
	}
	fmt.Fprintf(b, "\t\t\tvar inputValue %s\n", fnInputGoType(fn, alias))
	b.WriteString("\t\t\tif len(input) == 0 {\n")
	b.WriteString("\t\t\t\treturn nil, &rstf.RequestError{Code: rstf.ErrorCodeInvalidPayload, Message: \"input is required\", Status: http.StatusBadRequest}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tif err := json.Unmarshal(input, &inputValue); err != nil {\n")
	b.WriteString("\t\t\t\treturn nil, &rstf.RequestError{Code: rstf.ErrorCodeInvalidPayload, Message: \"invalid rpc input\", Status: http.StatusBadRequest}\n")
	b.WriteString("\t\t\t}\n")
}

func callInputSuffix(fn RouteFunc) string {
	if fn.InputType == "" {
		return ""
	}
	return ", inputValue"
}

func fnInputGoType(fn RouteFunc, alias string) string {
	if fn.InputType == "" {
		return ""
	}
	name := fn.InputType
	if !isPrimitiveGoType(fn.InputType) {
		name = alias + "." + name
	}
	if fn.InputIsSlice {
		return "[]" + name
	}
	return name
}

func returnsErrorOnly(fn RouteFunc) bool {
	return fn.ReturnType == "" && fn.ReturnsError
}

func returnsDataAndError(fn RouteFunc) bool {
	return fn.ReturnType != "" && fn.ReturnsError
}

func rpcFuncsByKind(funcs []RouteFunc, kind RouteFuncKind) []RouteFunc {
	var result []RouteFunc
	for _, fn := range funcs {
		if fn.Kind == kind {
			result = append(result, fn)
		}
	}
	return result
}

func rpcFuncsByKinds(funcs []RouteFunc, kinds ...RouteFuncKind) []RouteFunc {
	var result []RouteFunc
	for _, fn := range funcs {
		for _, kind := range kinds {
			if fn.Kind == kind {
				result = append(result, fn)
				break
			}
		}
	}
	return result
}

func writeMain(
	b *strings.Builder,
	routes []routeEntry,
	layout RouteFile,
	hasLayout bool,
	aliasMap map[string]serverImport,
	deps map[string][]string,
) {
	hasOnServerStart := hasLayout && layout.HasOnServerStart
	hasAroundRequest := hasLayout && layout.HasAroundRequest
	hasLayoutSSR := false
	if hasLayout {
		for _, fn := range layout.Funcs {
			if fn.Name == "SSR" {
				hasLayoutSSR = true
				break
			}
		}
	}

	b.WriteString(`func main() {
	port := flag.String("port", "3000", "HTTP server port")
	flag.Parse()

	rstfApp := rstf.NewApp()
	defer rstfApp.Close()
`)

	if hasOnServerStart {
		imp := aliasMap["."]
		fmt.Fprintf(b, `
	%s.OnServerStart(rstfApp)
`, imp.Alias)
	}

	b.WriteString(`
	r := renderer.New()
	if err := r.Start("."); err != nil {
		fmt.Fprintf(os.Stderr, "failed to start renderer: %s\n", err)
		os.Exit(1)
	}
	defer r.Stop()

	go func() {
		c := make(chan os.Signal, 1)
		signal.Notify(c, os.Interrupt, syscall.SIGTERM)
		<-c
		r.Stop()
		os.Exit(0)
	}()

	rt := router.New()
	admissionMiddleware := rstf.NewAdmissionMiddleware(rstf.AdmissionControlConfig{
		MaxConcurrentRequests: rstfApp.MaxConcurrentRequests(),
		MaxQueuedRequests:     rstfApp.MaxQueuedRequests(),
		QueueTimeout:          rstfApp.QueueTimeout(),
	})
	rt.Use(func(next http.Handler) http.Handler {
		admitted := admissionMiddleware(next)
		return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
			if strings.HasPrefix(req.URL.Path, "/__rstf/live") {
				next.ServeHTTP(w, req)
				return
			}
			admitted.ServeHTTP(w, req)
		})
	})
`)

	if hasAroundRequest {
		imp := aliasMap["."]
		fmt.Fprintf(b, `
	for _, mw := range %s.AroundRequest() {
		rt.Use(mw)
	}
`, imp.Alias)
	}

	b.WriteString(`
	rt.Handle("/.rstf/static/*", http.StripPrefix("/.rstf/static/", http.FileServer(http.Dir(".rstf/static"))))

	var cssPath string
	if _, err := os.Stat(".rstf/static/main.css"); err == nil {
		cssPath = "/.rstf/static/main.css"
	}

	liveHub := rstf.NewLiveHub()

	rt.Handle("/__rstf/live", http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if req.Method != http.MethodGet {
			methodNotAllowed(w, []string{http.MethodGet})
			return
		}
		clientID := strings.TrimSpace(req.URL.Query().Get("clientId"))
		if clientID == "" {
			writeNotAcceptable(w)
			return
		}
		w.Header().Set("Content-Type", "text/event-stream")
		w.Header().Set("Cache-Control", "no-cache")
		w.Header().Set("Connection", "keep-alive")

		events, disconnect := liveHub.Connect(clientID)
		defer disconnect()

		go liveHub.Replay(clientID)

		if flusher, ok := w.(http.Flusher); ok {
			flusher.Flush()
		}

		for {
			select {
			case <-req.Context().Done():
				return
			case event, ok := <-events:
				if !ok {
					return
				}
				if err := writeSSE(w, event); err != nil {
					return
				}
			}
		}
	}))

	rt.Handle("/__rstf/live/subscribe", http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if req.Method != http.MethodPost {
			methodNotAllowed(w, []string{http.MethodPost})
			return
		}
		var payload liveSubscribeRequest
		if err := decodeJSONBody(req, &payload); err != nil {
			rstf.WriteErrorEnvelope(w, err)
			return
		}
		key := rstf.NewSubscriptionKey(payload.Route, payload.Name, payload.Params)
		liveHub.Register(&rstf.LiveSubscription{
			ClientID:       payload.ClientID,
			SubscriptionID: payload.SubscriptionID,
			Key:            key,
			Execute: func() (any, error) {
				return executeQuery(req, rstfApp, payload.Route, payload.Name, payload.Params)
			},
		})
		result, err := executeQuery(req, rstfApp, payload.Route, payload.Name, payload.Params)
		if err != nil {
			rstf.WriteErrorEnvelope(w, err)
			return
		}
		writeRPCSuccess(w, result)
	}))

	rt.Handle("/__rstf/live/unsubscribe", http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if req.Method != http.MethodPost {
			methodNotAllowed(w, []string{http.MethodPost})
			return
		}
		var payload liveUnsubscribeRequest
		if err := decodeJSONBody(req, &payload); err != nil {
			rstf.WriteErrorEnvelope(w, err)
			return
		}
		liveHub.Unregister(payload.ClientID, payload.SubscriptionID)
		writeRPCSuccess(w, map[string]bool{"ok": true})
	}))

	rt.Handle("/__rstf/rpc", http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if req.Method != http.MethodPost {
			methodNotAllowed(w, []string{http.MethodPost})
			return
		}
		var payload rpcRequest
		if err := decodeJSONBody(req, &payload); err != nil {
			rstf.WriteErrorEnvelope(w, err)
			return
		}
		result, err := executeMutationOrAction(req, rstfApp, payload.Route, payload.Name, payload.Kind, payload.Params, payload.Input, liveHub)
		if err != nil {
			rstf.WriteErrorEnvelope(w, err)
			return
		}
		writeRPCSuccess(w, result)
	}))
`)

	for _, route := range routes {
		allowedMethods := []string{"OPTIONS"}
		if route.hasComponent || route.hasGET {
			allowedMethods = append(allowedMethods, "GET", "HEAD")
		}
		if route.hasPOST {
			allowedMethods = append(allowedMethods, "POST")
		}
		if route.hasPUT {
			allowedMethods = append(allowedMethods, "PUT")
		}
		if route.hasPATCH {
			allowedMethods = append(allowedMethods, "PATCH")
		}
		if route.hasDELETE {
			allowedMethods = append(allowedMethods, "DELETE")
		}

		fmt.Fprintf(b, "\n\trt.Handle(%q, http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {\n", route.urlPattern)
		fmt.Fprintf(b, "\t\tallowed := []string{%s}\n", quotedList(allowedMethods))
		b.WriteString(`		switch req.Method {
		case http.MethodOptions:
			writeOptions(w, allowed)
			return
		case http.MethodGet, http.MethodHead:
`)
		if route.hasComponent || route.hasGET {
			b.WriteString("\t\t\thead := req.Method == http.MethodHead\n")
			b.WriteString(`			isHTML := prefersHTML(req.Header.Get("Accept"))
			if isHTML {
`)
			if route.hasComponent {
				writeHTMLRenderBlock(b, route, hasLayoutSSR, aliasMap, deps)
			} else {
				b.WriteString("\t\t\t\twriteNotAcceptable(w)\n\t\t\t\treturn\n")
			}
			b.WriteString(`			}
`)
			if route.hasGET {
				writeMethodCallBlock(b, route, aliasMap, "GET", true)
			} else {
				b.WriteString("\t\t\twriteNotAcceptable(w)\n\t\t\treturn\n")
			}
		} else {
			b.WriteString("\t\t\twriteNotAcceptable(w)\n\t\t\treturn\n")
		}
		if route.hasPOST {
			b.WriteString("\t\tcase http.MethodPost:\n")
			writeMethodCallBlock(b, route, aliasMap, "POST", false)
		}
		if route.hasPUT {
			b.WriteString("\t\tcase http.MethodPut:\n")
			writeMethodCallBlock(b, route, aliasMap, "PUT", false)
		}
		if route.hasPATCH {
			b.WriteString("\t\tcase http.MethodPatch:\n")
			writeMethodCallBlock(b, route, aliasMap, "PATCH", false)
		}
		if route.hasDELETE {
			b.WriteString("\t\tcase http.MethodDelete:\n")
			writeMethodCallBlock(b, route, aliasMap, "DELETE", false)
		}
		b.WriteString(`		default:
			methodNotAllowed(w, allowed)
		}
	}))
`)
	}

	b.WriteString(`
	srv := &http.Server{
		Addr:              ":" + *port,
		Handler:           rt,
		ReadHeaderTimeout: rstfApp.ReadHeaderTimeout(),
		ReadTimeout:       rstfApp.ReadTimeout(),
		WriteTimeout:      rstfApp.WriteTimeout(),
		IdleTimeout:       rstfApp.IdleTimeout(),
	}

	if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		fmt.Fprintf(os.Stderr, "server error: %s\n", err)
		os.Exit(1)
	}
}
`)
}

func writeHTMLRenderBlock(
	b *strings.Builder,
	route routeEntry,
	hasLayoutSSR bool,
	aliasMap map[string]serverImport,
	deps map[string][]string,
) {
	b.WriteString("\t\t\t\tctx, err := newRequestContext(req, rstfApp)\n")
	b.WriteString("\t\t\t\tif err != nil {\n")
	b.WriteString("\t\t\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n")
	b.WriteString("\t\t\t\t\treturn\n")
	b.WriteString("\t\t\t\t}\n")

	b.WriteString("\t\t\t\tsd := map[string]map[string]any{}\n")
	if hasLayoutSSR {
		imp := aliasMap["."]
		fmt.Fprintf(b, "\t\t\t\tsd[\"main\"] = %s\n", ssrCall(imp.Alias, imp.HasContext))
	}
	for _, depDir := range deps[route.dir] {
		if depDir == "." {
			continue
		}
		imp, ok := aliasMap[depDir]
		if !ok || !imp.HasSSR {
			continue
		}
		fmt.Fprintf(b, "\t\t\t\tsd[%q] = %s\n", depDir, ssrCall(imp.Alias, imp.HasContext))
	}

	fmt.Fprintf(b, "\t\t\t\thtml, err := r.Render(renderer.RenderRequest{Component: %q, Layout: \"main\", ServerData: sd})\n", route.dir)
	b.WriteString("\t\t\t\tif err != nil {\n")
	b.WriteString("\t\t\t\t\thttp.Error(w, err.Error(), 500)\n")
	b.WriteString("\t\t\t\t\treturn\n")
	b.WriteString("\t\t\t\t}\n")
	fmt.Fprintf(b, "\t\t\t\tpage := assemblePage(html, sd, %q, cssPath)\n", bundlePath(route.dir))
	b.WriteString("\t\t\t\twriteHTMLResponse(w, page, head)\n")
	b.WriteString("\t\t\t\treturn\n")
}

func writeMethodCallBlock(
	b *strings.Builder,
	route routeEntry,
	aliasMap map[string]serverImport,
	methodName string,
	useHeadVar bool,
) {
	alias := aliasMap[route.dir].Alias
	if useHeadVar {
		fmt.Fprintf(b, "\t\t\tinvokeRouteAction(w, req, rstfApp, head, %s.%s)\n", alias, methodName)
	} else {
		fmt.Fprintf(b, "\t\t\t\tinvokeRouteAction(w, req, rstfApp, false, %s.%s)\n", alias, methodName)
	}
	b.WriteString("\t\t\t\treturn\n")
}

func ssrCall(alias string, hasContext bool) string {
	if hasContext {
		return fmt.Sprintf("structToMap(%s.SSR(ctx))", alias)
	}
	return fmt.Sprintf("structToMap(%s.SSR())", alias)
}

func quotedList(items []string) string {
	if len(items) == 0 {
		return ""
	}
	quoted := make([]string, 0, len(items))
	for _, item := range items {
		quoted = append(quoted, fmt.Sprintf("%q", item))
	}
	return strings.Join(quoted, ", ")
}

// ParseModulePath extracts the module path from go.mod content.
// Returns an empty string if no module directive is found.
func ParseModulePath(goModContent []byte) string {
	for _, line := range strings.Split(string(goModContent), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module "))
		}
	}
	return ""
}
