package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/rafbgarcia/rstf/internal/conventions"
)

// frameworkModule is the import path of the rstf framework itself.
const frameworkModule = "github.com/rafbgarcia/rstf"

// serverImport tracks a user-package import for the generated server file.
type serverImport struct {
	Alias      string // Go import alias (e.g. "app", "dashboard")
	ImportPath string // full import path
	Dir        string // project-relative dir (e.g. ".", "routes/dashboard")
	HasContext bool   // whether SSR() takes *rstf.Context
}

// routeEntry pairs a route directory with its computed URL pattern and handlers.
type routeEntry struct {
	dir           string
	urlPattern    string
	hasComponent  bool
	hasSSR        bool
	hasGET        bool
	hasPOST       bool
	hasPUT        bool
	hasPATCH      bool
	hasDELETE     bool
	ssrHasContext bool
}

// GenerateServer produces the content of .rstf/server_gen.go — the Go entry
// point that wires routes to handlers, calls route functions, and renders via
// the Node sidecar.
func GenerateServer(modulePath string, files []RouteFile, deps map[string][]string) (string, error) {
	fileMap := map[string]RouteFile{}
	for _, f := range files {
		fileMap[f.Dir] = f
	}

	layout, hasLayout := fileMap["."]

	if hasLayout && layout.Package == "main" {
		return "", fmt.Errorf(
			"main.go: package main is reserved for rstf, please use a different package name (e.g. your app name)",
		)
	}

	routeMap := map[string]routeEntry{}
	for _, f := range files {
		if !conventions.IsRouteDir(f.Dir) {
			continue
		}
		folder := strings.TrimPrefix(f.Dir, "routes/")
		e := routeEntry{
			dir:        f.Dir,
			urlPattern: conventions.FolderToURLPattern(folder),
		}
		for _, fn := range f.Funcs {
			switch fn.Name {
			case "SSR":
				e.hasSSR = true
				e.ssrHasContext = fn.HasContext
			case "GET":
				e.hasGET = true
			case "POST":
				e.hasPOST = true
			case "PUT":
				e.hasPUT = true
			case "PATCH":
				e.hasPATCH = true
			case "DELETE":
				e.hasDELETE = true
			}
		}
		routeMap[f.Dir] = e
	}

	for routeDir := range deps {
		if !conventions.IsRouteDir(routeDir) {
			continue
		}
		e := routeMap[routeDir]
		if e.dir == "" {
			folder := strings.TrimPrefix(routeDir, "routes/")
			e = routeEntry{dir: routeDir, urlPattern: conventions.FolderToURLPattern(folder)}
		}
		e.hasComponent = true
		routeMap[routeDir] = e
	}

	var routes []routeEntry
	for _, e := range routeMap {
		routes = append(routes, e)
	}
	sort.Slice(routes, func(i, j int) bool {
		return routes[i].urlPattern < routes[j].urlPattern
	})

	imports := collectImports(modulePath, layout, hasLayout, routes, deps, fileMap)

	aliasMap := map[string]serverImport{}
	for _, imp := range imports {
		aliasMap[imp.Dir] = imp
	}

	var b strings.Builder
	writeHeader(&b)
	writeImports(&b, imports)
	writeAcceptHelpers(&b)
	writeStructToMap(&b)
	writeAssemblePage(&b)
	writeRequestHelpers(&b)
	writeResponseHelpers(&b)
	writeMain(&b, routes, layout, hasLayout, aliasMap, deps)
	return b.String(), nil
}

// collectImports gathers all unique user-package imports across the layout and
// all routes, assigning collision-free aliases.
func collectImports(
	modulePath string,
	layout RouteFile,
	hasLayout bool,
	routes []routeEntry,
	deps map[string][]string,
	fileMap map[string]RouteFile,
) []serverImport {
	seen := map[string]bool{}
	usedAliases := map[string]int{}
	var imports []serverImport

	addImport := func(dir string) {
		if seen[dir] {
			return
		}
		seen[dir] = true

		rf, ok := fileMap[dir]
		if !ok {
			return
		}

		var importPath string
		var baseAlias string
		if dir == "." {
			importPath = modulePath
			baseAlias = "app"
		} else if strings.Contains(dir, "$") {
			importPath = modulePath + "/.rstf/pkgs/" + strings.ReplaceAll(dir, "$", "")
			baseAlias = rf.Package
		} else {
			importPath = modulePath + "/" + dir
			baseAlias = rf.Package
		}

		alias := baseAlias
		if count, exists := usedAliases[baseAlias]; exists {
			alias = fmt.Sprintf("%s%d", baseAlias, count+1)
		}
		usedAliases[baseAlias]++

		hasCtx := false
		for _, fn := range rf.Funcs {
			if fn.Name == "SSR" {
				hasCtx = fn.HasContext
				break
			}
		}

		imports = append(imports, serverImport{
			Alias:      alias,
			ImportPath: importPath,
			Dir:        dir,
			HasContext: hasCtx,
		})
	}

	if hasLayout {
		addImport(".")
	}

	for _, r := range routes {
		addImport(r.dir)
		for _, depDir := range deps[r.dir] {
			addImport(depDir)
		}
	}

	return imports
}

func writeHeader(b *strings.Builder) {
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
}

func writeImports(b *strings.Builder, imports []serverImport) {
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"flag\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"mime\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"os/signal\"\n")
	b.WriteString("\t\"strconv\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString("\t\"syscall\"\n")
	b.WriteString("\n")
	fmt.Fprintf(b, "\trstf %q\n", frameworkModule)
	fmt.Fprintf(b, "\t%q\n", frameworkModule+"/renderer")
	fmt.Fprintf(b, "\t%q\n", frameworkModule+"/router")
	b.WriteString("\n")
	for _, imp := range imports {
		fmt.Fprintf(b, "\t%s %q\n", imp.Alias, imp.ImportPath)
	}
	b.WriteString(")\n\n")
}

func writeAcceptHelpers(b *strings.Builder) {
	b.WriteString(`func prefersHTML(accept string) bool {
	accept = strings.TrimSpace(accept)
	if accept == "" {
		return true
	}

	hasAny := false
	hasWildcard := false
	parts := strings.Split(accept, ",")
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		mediaType, params, err := mime.ParseMediaType(part)
		if err != nil {
			continue
		}
		q := 1.0
		if qRaw, ok := params["q"]; ok {
			if parsed, err := strconv.ParseFloat(qRaw, 64); err == nil {
				q = parsed
			}
		}
		if q <= 0 {
			continue
		}
		hasAny = true

		mediaType = strings.ToLower(strings.TrimSpace(mediaType))
		if mediaType == "text/html" || mediaType == "application/xhtml+xml" {
			return true
		}
		if mediaType == "*/*" {
			hasWildcard = true
		}
	}

	if !hasAny {
		return true
	}
	return hasWildcard
}

func allowHeader(methods []string) string {
	return strings.Join(methods, ", ")
}

func methodNotAllowed(w http.ResponseWriter, methods []string) {
	w.Header().Set("Allow", allowHeader(methods))
	w.WriteHeader(http.StatusMethodNotAllowed)
}
`)
	b.WriteString("\n")
}

func writeStructToMap(b *strings.Builder) {
	b.WriteString(`func structToMap(v any) map[string]any {
	b, err := json.Marshal(v)
	if err != nil {
		return map[string]any{}
	}
	var m map[string]any
	if err := json.Unmarshal(b, &m); err != nil {
		return map[string]any{}
	}
	if m == nil {
		return map[string]any{}
	}
	return m
}`)
	b.WriteString("\n\n")
}

func writeAssemblePage(b *strings.Builder) {
	b.WriteString(`func assemblePage(html string, serverData map[string]map[string]any, bundlePath string, cssPath string) string {
	sdJSON, err := json.Marshal(serverData)
	if err != nil {
		sdJSON = []byte("{}")
	}
	dataScript := "<script>window.__RSTF_SERVER_DATA__ = " + string(sdJSON) + "</script>"
	bundleScript := "<script src=\"" + bundlePath + "\"></script>"
	page := "<!DOCTYPE html>" + html
	if cssPath != "" {
		page = strings.Replace(page, "</head>", "<link rel=\"stylesheet\" href=\""+cssPath+"\">\n</head>", 1)
	}
	page = strings.Replace(page, "</body>", dataScript+bundleScript+"</body>", 1)
	return page
}`)
	b.WriteString("\n\n")
}

func writeRequestHelpers(b *strings.Builder) {
	b.WriteString(`func newRequestContext(req *http.Request, rstfApp *rstf.App) (*rstf.Context, error) {
	ctx := rstf.NewContext(req)
	ctx.DB = rstfApp.DB()
	if err := ctx.SetRequestBodyLimitBytes(rstfApp.RequestBodyLimitBytes()); err != nil {
		return nil, err
	}
	return ctx, nil
}

func invokeRouteAction(
	w http.ResponseWriter,
	req *http.Request,
	rstfApp *rstf.App,
	head bool,
	action func(*rstf.Context) error,
) {
	tracker := rstf.NewResponseTracker(w)
	ctx, err := newRequestContext(req, rstfApp)
	if err != nil {
		if !tracker.Written() {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
		return
	}
	if head {
		ctx.Writer = rstf.NewHeadWriter(tracker)
	} else {
		ctx.Writer = tracker
	}
	if err := action(ctx); err != nil {
		if !tracker.Written() {
			rstf.WriteErrorEnvelope(tracker, err)
		}
		return
	}
	if !tracker.Written() {
		tracker.WriteHeader(http.StatusNoContent)
	}
}
`)
	b.WriteString("\n")
}

func writeResponseHelpers(b *strings.Builder) {
	b.WriteString(`func writeOptions(w http.ResponseWriter, methods []string) {
	w.Header().Set("Allow", allowHeader(methods))
	w.WriteHeader(http.StatusNoContent)
}

func writeNotAcceptable(w http.ResponseWriter) {
	w.WriteHeader(http.StatusNotAcceptable)
}

func writeHTMLResponse(w http.ResponseWriter, page string, head bool) {
	if head {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Header().Set("Content-Length", strconv.Itoa(len(page)))
		w.WriteHeader(http.StatusOK)
		return
	}
	fmt.Fprint(w, page)
}
`)
	b.WriteString("\n")
}

func writeMain(
	b *strings.Builder,
	routes []routeEntry,
	layout RouteFile,
	hasLayout bool,
	aliasMap map[string]serverImport,
	deps map[string][]string,
) {
	hasOnServerStart := hasLayout && layout.HasOnServerStart
	hasAroundRequest := hasLayout && layout.HasAroundRequest
	hasLayoutSSR := false
	if hasLayout {
		for _, fn := range layout.Funcs {
			if fn.Name == "SSR" {
				hasLayoutSSR = true
				break
			}
		}
	}

	b.WriteString(`func main() {
	port := flag.String("port", "3000", "HTTP server port")
	flag.Parse()

	rstfApp := rstf.NewApp()
	defer rstfApp.Close()
`)

	if hasOnServerStart {
		imp := aliasMap["."]
		fmt.Fprintf(b, `
	%s.OnServerStart(rstfApp)
`, imp.Alias)
	}

	b.WriteString(`
	r := renderer.New()
	if err := r.Start("."); err != nil {
		fmt.Fprintf(os.Stderr, "failed to start renderer: %s\n", err)
		os.Exit(1)
	}
	defer r.Stop()

	go func() {
		c := make(chan os.Signal, 1)
		signal.Notify(c, os.Interrupt, syscall.SIGTERM)
		<-c
		r.Stop()
		os.Exit(0)
	}()

	rt := router.New()
	rt.Use(rstf.NewAdmissionMiddleware(rstf.AdmissionControlConfig{
		MaxConcurrentRequests: rstfApp.MaxConcurrentRequests(),
		MaxQueuedRequests:     rstfApp.MaxQueuedRequests(),
		QueueTimeout:          rstfApp.QueueTimeout(),
	}))
`)

	if hasAroundRequest {
		imp := aliasMap["."]
		fmt.Fprintf(b, `
	for _, mw := range %s.AroundRequest() {
		rt.Use(mw)
	}
`, imp.Alias)
	}

	b.WriteString(`
	rt.Handle("/.rstf/static/*", http.StripPrefix("/.rstf/static/", http.FileServer(http.Dir(".rstf/static"))))

	var cssPath string
	if _, err := os.Stat(".rstf/static/main.css"); err == nil {
		cssPath = "/.rstf/static/main.css"
	}
`)

	for _, route := range routes {
		allowedMethods := []string{"OPTIONS"}
		if route.hasComponent || route.hasGET {
			allowedMethods = append(allowedMethods, "GET", "HEAD")
		}
		if route.hasPOST {
			allowedMethods = append(allowedMethods, "POST")
		}
		if route.hasPUT {
			allowedMethods = append(allowedMethods, "PUT")
		}
		if route.hasPATCH {
			allowedMethods = append(allowedMethods, "PATCH")
		}
		if route.hasDELETE {
			allowedMethods = append(allowedMethods, "DELETE")
		}

		fmt.Fprintf(b, "\n\trt.Handle(%q, http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {\n", route.urlPattern)
		fmt.Fprintf(b, "\t\tallowed := []string{%s}\n", quotedList(allowedMethods))
		b.WriteString(`		switch req.Method {
		case http.MethodOptions:
			writeOptions(w, allowed)
			return
		case http.MethodGet, http.MethodHead:
`)
		if route.hasComponent || route.hasGET {
			b.WriteString("\t\t\thead := req.Method == http.MethodHead\n")
			b.WriteString(`			isHTML := prefersHTML(req.Header.Get("Accept"))
			if isHTML {
`)
			if route.hasComponent {
				writeHTMLRenderBlock(b, route, hasLayoutSSR, aliasMap, deps)
			} else {
				b.WriteString("\t\t\t\twriteNotAcceptable(w)\n\t\t\t\treturn\n")
			}
			b.WriteString(`			}
`)
			if route.hasGET {
				writeMethodCallBlock(b, route, aliasMap, "GET", true)
			} else {
				b.WriteString("\t\t\twriteNotAcceptable(w)\n\t\t\treturn\n")
			}
		} else {
			b.WriteString("\t\t\twriteNotAcceptable(w)\n\t\t\treturn\n")
		}
		if route.hasPOST {
			b.WriteString("\t\tcase http.MethodPost:\n")
			writeMethodCallBlock(b, route, aliasMap, "POST", false)
		}
		if route.hasPUT {
			b.WriteString("\t\tcase http.MethodPut:\n")
			writeMethodCallBlock(b, route, aliasMap, "PUT", false)
		}
		if route.hasPATCH {
			b.WriteString("\t\tcase http.MethodPatch:\n")
			writeMethodCallBlock(b, route, aliasMap, "PATCH", false)
		}
		if route.hasDELETE {
			b.WriteString("\t\tcase http.MethodDelete:\n")
			writeMethodCallBlock(b, route, aliasMap, "DELETE", false)
		}
		b.WriteString(`		default:
			methodNotAllowed(w, allowed)
		}
	}))
`)
	}

	b.WriteString(`
	if err := http.ListenAndServe(":"+*port, rt); err != nil {
		fmt.Fprintf(os.Stderr, "server error: %s\n", err)
		os.Exit(1)
	}
}
`)
}

func writeHTMLRenderBlock(
	b *strings.Builder,
	route routeEntry,
	hasLayoutSSR bool,
	aliasMap map[string]serverImport,
	deps map[string][]string,
) {
	b.WriteString("\t\t\t\tctx, err := newRequestContext(req, rstfApp)\n")
	b.WriteString("\t\t\t\tif err != nil {\n")
	b.WriteString("\t\t\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n")
	b.WriteString("\t\t\t\t\treturn\n")
	b.WriteString("\t\t\t\t}\n")

	b.WriteString("\t\t\t\tsd := map[string]map[string]any{}\n")
	if hasLayoutSSR {
		imp := aliasMap["."]
		fmt.Fprintf(b, "\t\t\t\tsd[\"main\"] = %s\n", ssrCall(imp.Alias, imp.HasContext))
	}
	for _, depDir := range deps[route.dir] {
		if depDir == "." {
			continue
		}
		imp, ok := aliasMap[depDir]
		if !ok {
			continue
		}
		fmt.Fprintf(b, "\t\t\t\tsd[%q] = %s\n", depDir, ssrCall(imp.Alias, imp.HasContext))
	}

	fmt.Fprintf(b, "\t\t\t\thtml, err := r.Render(renderer.RenderRequest{Component: %q, Layout: \"main\", ServerData: sd})\n", route.dir)
	b.WriteString("\t\t\t\tif err != nil {\n")
	b.WriteString("\t\t\t\t\thttp.Error(w, err.Error(), 500)\n")
	b.WriteString("\t\t\t\t\treturn\n")
	b.WriteString("\t\t\t\t}\n")
	fmt.Fprintf(b, "\t\t\t\tpage := assemblePage(html, sd, %q, cssPath)\n", bundlePath(route.dir))
	b.WriteString("\t\t\t\twriteHTMLResponse(w, page, head)\n")
	b.WriteString("\t\t\t\treturn\n")
}

func writeMethodCallBlock(
	b *strings.Builder,
	route routeEntry,
	aliasMap map[string]serverImport,
	methodName string,
	useHeadVar bool,
) {
	alias := aliasMap[route.dir].Alias
	if useHeadVar {
		fmt.Fprintf(b, "\t\t\tinvokeRouteAction(w, req, rstfApp, head, %s.%s)\n", alias, methodName)
	} else {
		fmt.Fprintf(b, "\t\t\t\tinvokeRouteAction(w, req, rstfApp, false, %s.%s)\n", alias, methodName)
	}
	b.WriteString("\t\t\t\treturn\n")
}

func ssrCall(alias string, hasContext bool) string {
	if hasContext {
		return fmt.Sprintf("structToMap(%s.SSR(ctx))", alias)
	}
	return fmt.Sprintf("structToMap(%s.SSR())", alias)
}

func quotedList(items []string) string {
	if len(items) == 0 {
		return ""
	}
	quoted := make([]string, 0, len(items))
	for _, item := range items {
		quoted = append(quoted, fmt.Sprintf("%q", item))
	}
	return strings.Join(quoted, ", ")
}

// ParseModulePath extracts the module path from go.mod content.
// Returns an empty string if no module directive is found.
func ParseModulePath(goModContent []byte) string {
	for _, line := range strings.Split(string(goModContent), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module "))
		}
	}
	return ""
}
