package codegen

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// assemblePage mirrors the generated assemblePage function from writeAssemblePage
// so we can unit-test the CSS link injection logic directly.
func assemblePage(html string, serverData map[string]map[string]any, bundlePath string, cssPath string) string {
	sdJSON, _ := json.Marshal(serverData)
	dataScript := "<script>window.__RSTF_SERVER_DATA__ = " + string(sdJSON) + "</script>"
	bundleScript := "<script src=\"" + bundlePath + "\"></script>"
	page := "<!DOCTYPE html>" + html
	if cssPath != "" {
		page = strings.Replace(page, "</head>", "<link rel=\"stylesheet\" href=\""+cssPath+"\">\n</head>", 1)
	}
	page = strings.Replace(page, "</body>", dataScript+bundleScript+"</body>", 1)
	return page
}

func TestAssemblePage_WithCSS(t *testing.T) {
	html := "<html><head><title>Test</title></head><body><h1>Hello</h1></body></html>"
	sd := map[string]map[string]any{"main": {"key": "val"}}
	cssPath := "/rstf/static/main.css"

	got := assemblePage(html, sd, "/rstf/static/dashboard/bundle.js", cssPath)

	checks := []struct {
		desc string
		want string
	}{
		{"doctype", "<!DOCTYPE html>"},
		{"css link tag", `<link rel="stylesheet" href="/rstf/static/main.css">`},
		{"css before </head>", `main.css">` + "\n</head>"},
		{"data script", `window.__RSTF_SERVER_DATA__`},
		{"bundle script", `<script src="/rstf/static/dashboard/bundle.js"></script>`},
	}
	for _, c := range checks {
		assert.Contains(t, got, c.want, "%s: output missing %q\n\nFull output:\n%s", c.desc, c.want, got)
	}

	// CSS link must appear before </head>, not in the body.
	linkIdx := strings.Index(got, `<link rel="stylesheet"`)
	headIdx := strings.Index(got, "</head>")
	bodyIdx := strings.Index(got, "<body>")
	assert.LessOrEqual(t, linkIdx, headIdx, "CSS link should appear before </head>")
	assert.LessOrEqual(t, linkIdx, bodyIdx, "CSS link should appear before <body>")
}

func TestAssemblePage_WithoutCSS(t *testing.T) {
	html := "<html><head><title>Test</title></head><body><h1>Hello</h1></body></html>"
	sd := map[string]map[string]any{"main": {"key": "val"}}

	got := assemblePage(html, sd, "/rstf/static/dashboard/bundle.js", "")

	assert.NotContains(t, got, "<link", "should not contain <link> tag when cssPath is empty\n\nFull output:\n%s", got)

	// Should still have doctype and scripts.
	for _, want := range []string{"<!DOCTYPE html>", "window.__RSTF_SERVER_DATA__", `<script src="`} {
		assert.Contains(t, got, want, "output missing %q\n\nFull output:\n%s", want, got)
	}
}

func TestGenerateServer_SingleRoute(t *testing.T) {
	files := []RouteFile{
		{
			Dir:     ".",
			Package: "myapp",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "Session", HasContext: true}},
			Structs: []StructDef{{Name: "Session"}},
		},
		{
			Dir:     "routes/dashboard",
			Package: "dashboard",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
	}
	deps := map[string][]string{
		"routes/dashboard": {"routes/dashboard"},
	}

	got, err := GenerateServer("github.com/user/myapp", files, deps)
	require.NoError(t, err)

	expectations := []string{
		"// Code generated by rstf. DO NOT EDIT.",
		"package main",
		`"encoding/json"`,
		`"flag"`,
		`"fmt"`,
		`"net/http"`,
		`"os"`,
		`"os/signal"`,
		`"strings"`,
		`"syscall"`,
		`rstf "github.com/rafbgarcia/rstf"`,
		`"github.com/rafbgarcia/rstf/renderer"`,
		`"github.com/rafbgarcia/rstf/router"`,
		`app "github.com/user/myapp"`,
		`dashboard "github.com/user/myapp/routes/dashboard"`,
		"func structToMap(v any) map[string]any {",
		"func assemblePage(html string, serverData map[string]map[string]any, bundlePath string, cssPath string) string {",
		"window.__RSTF_SERVER_DATA__",
		"func main() {",
		"r := renderer.New()",
		`if err := r.Start("."); err != nil`,
		`defer r.Stop()`,
		`signal.Notify(c, os.Interrupt, syscall.SIGTERM)`,
		`rt := router.New()`,
		`rt.Handle("/rstf/static/*"`,
		`rt.Handle("/dashboard"`,
		"ctx := rstf.NewContext(req)",
		`sd["main"] = structToMap(app.SSR(ctx))`,
		`sd["routes/dashboard"] = structToMap(dashboard.SSR(ctx))`,
		"allowed := []string{\"OPTIONS\", \"GET\", \"HEAD\"}",
		`w.WriteHeader(http.StatusNotAcceptable)`,
		`Component: "routes/dashboard"`,
		`Layout: "main"`,
		`http.Error(w, err.Error(), 500)`,
		`assemblePage(html, sd, "/rstf/static/dashboard/bundle.js", cssPath)`,
		`os.Stat("rstf/static/main.css")`,
		`flag.String("port", "3000", "HTTP server port")`,
		`flag.Parse()`,
		`srv := &http.Server{`,
		`ReadHeaderTimeout: rstfApp.ReadHeaderTimeout()`,
		`ReadTimeout:       rstfApp.ReadTimeout()`,
		`WriteTimeout:      rstfApp.WriteTimeout()`,
		`IdleTimeout:       rstfApp.IdleTimeout()`,
		`srv.ListenAndServe()`,
	}

	for _, exp := range expectations {
		assert.Contains(t, got, exp, "output missing %q\n\nFull output:\n%s", exp, got)
	}
}

func TestGenerateServer_MultipleRoutes(t *testing.T) {
	files := []RouteFile{
		{
			Dir:     ".",
			Package: "myapp",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "Session", HasContext: true}},
			Structs: []StructDef{{Name: "Session"}},
		},
		{
			Dir:     "routes/index",
			Package: "index",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
		{
			Dir:     "routes/dashboard",
			Package: "dashboard",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
		{
			Dir:     "routes/users._id.edit",
			Package: "useredit",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
	}
	deps := map[string][]string{
		"routes/index":          {"routes/index"},
		"routes/dashboard":      {"routes/dashboard"},
		"routes/users._id.edit": {"routes/users._id.edit"},
	}

	got, err := GenerateServer("github.com/user/myapp", files, deps)
	require.NoError(t, err)

	// Verify all three handlers exist.
	expectations := []string{
		`rt.Handle("/",`,
		`rt.Handle("/dashboard",`,
		`rt.Handle("/users/{id}/edit",`,
		`useredit "github.com/user/myapp/routes/users._id.edit"`,
	}
	for _, exp := range expectations {
		assert.Contains(t, got, exp, "output missing %q\n\nFull output:\n%s", exp, got)
	}

	// Verify routes are sorted: / comes before /dashboard comes before /users/{id}/edit.
	idxRoot := strings.Index(got, `rt.Handle("/",`)
	idxDash := strings.Index(got, `rt.Handle("/dashboard",`)
	idxUser := strings.Index(got, `rt.Handle("/users/{id}/edit",`)
	assert.Less(t, idxRoot, idxDash, "routes not sorted by URL pattern: / at %d, /dashboard at %d, /users/{id}/edit at %d", idxRoot, idxDash, idxUser)
	assert.Less(t, idxDash, idxUser, "routes not sorted by URL pattern: / at %d, /dashboard at %d, /users/{id}/edit at %d", idxRoot, idxDash, idxUser)

	// Verify bundle paths.
	bundleExpectations := []string{
		`"/rstf/static/index/bundle.js"`,
		`"/rstf/static/dashboard/bundle.js"`,
		`"/rstf/static/users-id-edit/bundle.js"`,
	}
	for _, exp := range bundleExpectations {
		assert.Contains(t, got, exp, "output missing bundle path %q\n\nFull output:\n%s", exp, got)
	}
}

func TestGenerateServer_SharedDeps(t *testing.T) {
	files := []RouteFile{
		{
			Dir:     ".",
			Package: "myapp",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "Session", HasContext: true}},
			Structs: []StructDef{{Name: "Session"}},
		},
		{
			Dir:     "routes/dashboard",
			Package: "dashboard",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
		{
			Dir:     "shared/ui/user-avatar",
			Package: "useravatar",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
	}
	deps := map[string][]string{
		"routes/dashboard": {"routes/dashboard", "shared/ui/user-avatar"},
	}

	got, err := GenerateServer("github.com/user/myapp", files, deps)
	require.NoError(t, err)

	expectations := []string{
		`useravatar "github.com/user/myapp/shared/ui/user-avatar"`,
		`sd["shared/ui/user-avatar"] = structToMap(useravatar.SSR(ctx))`,
	}
	for _, exp := range expectations {
		assert.Contains(t, got, exp, "output missing %q\n\nFull output:\n%s", exp, got)
	}
}

func TestGenerateServer_RouteWithoutGoFile(t *testing.T) {
	// Route "about" has no .go file — only a .tsx. It should still get a handler
	// but with no route SSR call in ServerData.
	files := []RouteFile{
		{
			Dir:     ".",
			Package: "myapp",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "Session", HasContext: true}},
			Structs: []StructDef{{Name: "Session"}},
		},
	}
	deps := map[string][]string{
		"routes/about": {}, // no deps — the route has no .go, no shared deps with .go
	}

	got, err := GenerateServer("github.com/user/myapp", files, deps)
	require.NoError(t, err)

	// Should still have a handler for /about.
	assert.Contains(t, got, `rt.Handle("/about",`, "output missing handler for /about\n\nFull output:\n%s", got)

	// Should have layout SSR but NOT a route SSR call.
	assert.Contains(t, got, `sd["main"] = structToMap(app.SSR(ctx))`, "output missing layout SSR call\n\nFull output:\n%s", got)

	// Should not contain "routes/about" as a ServerData key (it appears in Component, which is fine).
	assert.NotContains(t, got, `sd["routes/about"] = structToMap`, "output should not contain routes/about ServerData entry\n\nFull output:\n%s", got)
}

func TestGenerateServer_SSRWithoutContext(t *testing.T) {
	files := []RouteFile{
		{
			Dir:     ".",
			Package: "myapp",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "Session", HasContext: false}},
			Structs: []StructDef{{Name: "Session"}},
		},
		{
			Dir:     "routes/dashboard",
			Package: "dashboard",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: false}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
	}
	deps := map[string][]string{
		"routes/dashboard": {"routes/dashboard"},
	}

	got, err := GenerateServer("github.com/user/myapp", files, deps)
	require.NoError(t, err)

	// SSR calls should not pass ctx.
	assert.Contains(t, got, "structToMap(app.SSR())", "expected app.SSR() without ctx\n\nFull output:\n%s", got)
	assert.Contains(t, got, "structToMap(dashboard.SSR())", "expected dashboard.SSR() without ctx\n\nFull output:\n%s", got)
}

func TestGenerateServer_AliasCollision(t *testing.T) {
	// Two packages both named "index" — need unique aliases.
	files := []RouteFile{
		{
			Dir:     ".",
			Package: "myapp",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "Session", HasContext: true}},
			Structs: []StructDef{{Name: "Session"}},
		},
		{
			Dir:     "routes/index",
			Package: "index",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
		{
			Dir:     "routes/admin.index",
			Package: "index",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
	}
	deps := map[string][]string{
		"routes/index":       {"routes/index"},
		"routes/admin.index": {"routes/admin.index"},
	}

	got, err := GenerateServer("github.com/user/myapp", files, deps)
	require.NoError(t, err)

	// One should be "index", the other "index2".
	assert.Contains(t, got, `index "github.com/user/myapp/routes/index"`, "expected index alias\n\nFull output:\n%s", got)
	assert.Contains(t, got, `index2 "github.com/user/myapp/routes/admin.index"`, "expected index2 alias for collision\n\nFull output:\n%s", got)
}

func TestGenerateServer_NoLayout(t *testing.T) {
	// Edge case: no layout .go file. Should still generate handlers.
	files := []RouteFile{
		{
			Dir:     "routes/dashboard",
			Package: "dashboard",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
	}
	deps := map[string][]string{
		"routes/dashboard": {"routes/dashboard"},
	}

	got, err := GenerateServer("github.com/user/myapp", files, deps)
	require.NoError(t, err)

	assert.Contains(t, got, `rt.Handle("/dashboard",`, "output missing handler\n\nFull output:\n%s", got)
	// Should NOT have layout import or SSR call.
	assert.NotContains(t, got, `app "github.com/user/myapp"`, "should not have layout import\n\nFull output:\n%s", got)
	assert.NotContains(t, got, `"main": structToMap`, "should not have layout ServerData entry\n\nFull output:\n%s", got)
}

func TestGenerateServer_WithOnServerStart(t *testing.T) {
	files := []RouteFile{
		{
			Dir:              ".",
			Package:          "myapp",
			Funcs:            []RouteFunc{{Name: "SSR", ReturnType: "Session", HasContext: true}},
			Structs:          []StructDef{{Name: "Session"}},
			HasOnServerStart: true,
		},
		{
			Dir:     "routes/dashboard",
			Package: "dashboard",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
	}
	deps := map[string][]string{
		"routes/dashboard": {"routes/dashboard"},
	}

	got, err := GenerateServer("github.com/user/myapp", files, deps)
	require.NoError(t, err)

	expectations := []string{
		// OnServerStart initialization at startup.
		"rstfApp := rstf.NewApp()",
		"app.OnServerStart(rstfApp)",
		"defer rstfApp.Close()",
		"admissionMiddleware := rstf.NewAdmissionMiddleware",
		`strings.HasPrefix(req.URL.Path, "/__rstf/live")`,
		// DB wiring in handler.
		"ctx.DB = rstfApp.DB()",
		"ctx.SetRequestBodyLimitBytes(rstfApp.RequestBodyLimitBytes())",
	}
	for _, exp := range expectations {
		assert.Contains(t, got, exp, "output missing %q\n\nFull output:\n%s", exp, got)
	}
}

func TestGenerateServer_WithoutOnServerStart(t *testing.T) {
	files := []RouteFile{
		{
			Dir:              ".",
			Package:          "myapp",
			Funcs:            []RouteFunc{{Name: "SSR", ReturnType: "Session", HasContext: true}},
			Structs:          []StructDef{{Name: "Session"}},
			HasOnServerStart: false,
		},
		{
			Dir:     "routes/dashboard",
			Package: "dashboard",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
	}
	deps := map[string][]string{
		"routes/dashboard": {"routes/dashboard"},
	}

	got, err := GenerateServer("github.com/user/myapp", files, deps)
	require.NoError(t, err)

	// Should NOT have OnServerStart call, but app/runtime defaults still wire context.
	unwanted := []string{
		"app.OnServerStart(",
	}
	for _, s := range unwanted {
		assert.NotContains(t, got, s, "output should NOT contain %q when HasOnServerStart=false\n\nFull output:\n%s", s, got)
	}
	required := []string{
		"rstfApp := rstf.NewApp()",
		"defer rstfApp.Close()",
		"admissionMiddleware := rstf.NewAdmissionMiddleware",
		`strings.HasPrefix(req.URL.Path, "/__rstf/live")`,
		"ctx.DB = rstfApp.DB()",
		"ctx.SetRequestBodyLimitBytes(rstfApp.RequestBodyLimitBytes())",
	}
	for _, s := range required {
		assert.Contains(t, got, s, "output missing %q when HasOnServerStart=false\n\nFull output:\n%s", s, got)
	}
}

func TestGenerateServer_OnServerStartOnlyLayout(t *testing.T) {
	// Layout has OnServerStart but no SSR function.
	files := []RouteFile{
		{
			Dir:              ".",
			Package:          "myapp",
			HasOnServerStart: true,
			// No Funcs — layout configures the app but doesn't return server data.
		},
		{
			Dir:     "routes/dashboard",
			Package: "dashboard",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
	}
	deps := map[string][]string{
		"routes/dashboard": {"routes/dashboard"},
	}

	got, err := GenerateServer("github.com/user/myapp", files, deps)
	require.NoError(t, err)

	// Should have OnServerStart initialization.
	assert.Contains(t, got, "rstfApp := rstf.NewApp()", "output missing OnServerStart initialization\n\nFull output:\n%s", got)
	assert.Contains(t, got, "app.OnServerStart(rstfApp)", "output missing app.OnServerStart call\n\nFull output:\n%s", got)

	// Should NOT have layout SSR call (no SSR function).
	assert.NotContains(t, got, `"main": structToMap`, "should not have layout SSR entry when layout has no SSR\n\nFull output:\n%s", got)
}

func TestGenerateServer_WithAroundRequest(t *testing.T) {
	files := []RouteFile{
		{
			Dir:              ".",
			Package:          "myapp",
			Funcs:            []RouteFunc{{Name: "SSR", ReturnType: "Session", HasContext: true}},
			Structs:          []StructDef{{Name: "Session"}},
			HasAroundRequest: true,
		},
		{
			Dir:     "routes/dashboard",
			Package: "dashboard",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
	}
	deps := map[string][]string{
		"routes/dashboard": {"routes/dashboard"},
	}

	got, err := GenerateServer("github.com/user/myapp", files, deps)
	require.NoError(t, err)

	expectations := []string{
		"rstfApp := rstf.NewApp()",
		"admissionMiddleware := rstf.NewAdmissionMiddleware",
		`strings.HasPrefix(req.URL.Path, "/__rstf/live")`,
		"app.AroundRequest()",
		"rt.Use(mw)",
	}
	for _, exp := range expectations {
		assert.Contains(t, got, exp, "output missing %q\n\nFull output:\n%s", exp, got)
	}

	// Should NOT have OnServerStart call.
	assert.NotContains(t, got, "app.OnServerStart(", "output should NOT contain OnServerStart call when only AroundRequest is set\n\nFull output:\n%s", got)
}

func TestGenerateServer_WithBothConventions(t *testing.T) {
	files := []RouteFile{
		{
			Dir:              ".",
			Package:          "myapp",
			Funcs:            []RouteFunc{{Name: "SSR", ReturnType: "Session", HasContext: true}},
			Structs:          []StructDef{{Name: "Session"}},
			HasOnServerStart: true,
			HasAroundRequest: true,
		},
		{
			Dir:     "routes/dashboard",
			Package: "dashboard",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
	}
	deps := map[string][]string{
		"routes/dashboard": {"routes/dashboard"},
	}

	got, err := GenerateServer("github.com/user/myapp", files, deps)
	require.NoError(t, err)

	expectations := []string{
		// OnServerStart
		"rstfApp := rstf.NewApp()",
		"app.OnServerStart(rstfApp)",
		"defer rstfApp.Close()",
		"admissionMiddleware := rstf.NewAdmissionMiddleware",
		`strings.HasPrefix(req.URL.Path, "/__rstf/live")`,
		"ctx.DB = rstfApp.DB()",
		"ctx.SetRequestBodyLimitBytes(rstfApp.RequestBodyLimitBytes())",
		// AroundRequest
		"app.AroundRequest()",
		"rt.Use(mw)",
	}
	for _, exp := range expectations {
		assert.Contains(t, got, exp, "output missing %q\n\nFull output:\n%s", exp, got)
	}

	// AroundRequest loop must appear after router creation but before route handlers.
	rtNewIdx := strings.Index(got, "rt := router.New()")
	aroundIdx := strings.Index(got, "app.AroundRequest()")
	routeIdx := strings.Index(got, `rt.Handle("/dashboard",`)
	assert.GreaterOrEqual(t, aroundIdx, rtNewIdx, "AroundRequest should appear after router creation")
	assert.LessOrEqual(t, aroundIdx, routeIdx, "AroundRequest should appear before route handlers")
}

func TestParseModulePath(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    string
	}{
		{
			name:    "standard",
			content: "module github.com/user/myapp\n\ngo 1.22\n",
			want:    "github.com/user/myapp",
		},
		{
			name:    "with extra whitespace",
			content: "  module   github.com/user/myapp  \n",
			want:    "github.com/user/myapp",
		},
		{
			name:    "no module line",
			content: "go 1.22\n",
			want:    "",
		},
		{
			name:    "commented out",
			content: "// module github.com/old\nmodule github.com/user/myapp\n",
			want:    "github.com/user/myapp",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ParseModulePath([]byte(tt.content))
			assert.Equal(t, tt.want, got, "ParseModulePath()")
		})
	}
}

func TestGenerateServer_RejectsPackageMain(t *testing.T) {
	files := []RouteFile{
		{
			Dir:     ".",
			Package: "main",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "Session", HasContext: true}},
			Structs: []StructDef{{Name: "Session"}},
		},
		{
			Dir:     "routes/dashboard",
			Package: "dashboard",
			Funcs:   []RouteFunc{{Name: "SSR", ReturnType: "ServerData", HasContext: true}},
			Structs: []StructDef{{Name: "ServerData"}},
		},
	}
	deps := map[string][]string{
		"routes/dashboard": {"routes/dashboard"},
	}

	_, err := GenerateServer("github.com/user/myapp", files, deps)
	require.Error(t, err, "expected error for package main in layout, got nil")
	assert.Contains(t, err.Error(), "reserved for rstf", "error should mention package main, got: %s", err)
}
