package codegen

import (
	"fmt"
	"path/filepath"
	"strings"
)

// Namespace returns the PascalCase namespace name for a route directory path.
// Examples: "dashboard" -> "Dashboard", "users/profile" -> "UsersProfile"
func Namespace(dir string) string {
	if dir == "." {
		return "Main"
	}
	parts := strings.Split(filepath.ToSlash(dir), "/")
	var result strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		result.WriteString(ucFirst(part))
	}
	return result.String()
}

// GenerateDTS produces a TypeScript declaration file (.d.ts) with a declare namespace
// for a parsed RouteFile. The types are globally available without imports.
func GenerateDTS(rf RouteFile) string {
	ns := Namespace(rf.Dir)
	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "declare namespace %s {\n", ns)

	// Write interfaces for each struct (including the ServerData return type).
	for i, sd := range rf.Structs {
		fmt.Fprintf(&b, "  interface %s {\n", sd.Name)
		for _, f := range sd.Fields {
			fmt.Fprintf(&b, "    %s: %s;\n", f.JSONName, f.Type)
		}
		b.WriteString("  }\n")
		if i < len(rf.Structs)-1 {
			b.WriteString("\n")
		}
	}

	b.WriteString("}\n")
	return b.String()
}

// GenerateRuntimeModule produces the .rstf/generated/{path}.ts module that exports
// a serverData() function and an internal __setServerData() function.
func GenerateRuntimeModule(rf RouteFile) string {
	if len(rf.Funcs) == 0 {
		return ""
	}

	fn := rf.Funcs[0]
	ns := Namespace(rf.Dir)

	// Verify the return struct exists.
	found := false
	for _, s := range rf.Structs {
		if s.Name == fn.ReturnType {
			found = true
			break
		}
	}
	if !found {
		return ""
	}

	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")
	b.WriteString("let _data: Record<string, any> = {};\n\n")

	// serverData() function — returns _data directly. The Go side always
	// provides complete data via json.Marshal, so all fields are present.
	fmt.Fprintf(&b, "export function serverData(): %s.%s {\n", ns, fn.ReturnType)
	fmt.Fprintf(&b, "  return _data as %s.%s;\n", ns, fn.ReturnType)
	b.WriteString("}\n\n")

	// __setServerData() function
	b.WriteString("export function __setServerData(data: Record<string, any>) {\n")
	b.WriteString("  _data = data;\n")
	b.WriteString("}\n")

	return b.String()
}
