package codegen

import (
	"strings"
	"testing"
)

func TestGenerateDTS_Dashboard(t *testing.T) {
	rf := RouteFile{
		Dir:     "dashboard",
		Package: "dashboard",
		Funcs: []RouteFunc{
			{
				Name:       "SSR",
				ReturnType: "ServerData",
			},
		},
		Structs: []StructDef{
			{
				Name: "Post",
				Fields: []StructField{
					{Name: "Title", JSONName: "title", Type: "string"},
					{Name: "Published", JSONName: "published", Type: "boolean"},
				},
			},
			{
				Name: "Author",
				Fields: []StructField{
					{Name: "Name", JSONName: "name", Type: "string"},
					{Name: "Email", JSONName: "email", Type: "string"},
				},
			},
			{
				Name: "ServerData",
				Fields: []StructField{
					{Name: "Posts", JSONName: "posts", Type: "Post[]"},
					{Name: "Author", JSONName: "author", Type: "Author"},
				},
			},
		},
	}

	got := GenerateDTS(rf)

	expectations := []string{
		"// Code generated by rstf. DO NOT EDIT.",
		"declare namespace Dashboard {",
		"  interface Post {",
		"    title: string;",
		"    published: boolean;",
		"  interface Author {",
		"    name: string;",
		"    email: string;",
		"  interface ServerData {",
		"    posts: Post[];",
		"    author: Author;",
	}

	for _, exp := range expectations {
		if !strings.Contains(got, exp) {
			t.Errorf("output missing %q\n\nFull output:\n%s", exp, got)
		}
	}
}

func TestGenerateDTS_PrimitiveTypes(t *testing.T) {
	rf := RouteFile{
		Dir:     "settings",
		Package: "settings",
		Funcs: []RouteFunc{
			{
				Name:       "SSR",
				ReturnType: "ServerData",
			},
		},
		Structs: []StructDef{
			{
				Name: "Config",
				Fields: []StructField{
					{Name: "Theme", JSONName: "theme", Type: "string"},
					{Name: "FontSize", JSONName: "fontSize", Type: "number"},
					{Name: "Beta", JSONName: "beta", Type: "boolean"},
					{Name: "Score", JSONName: "score", Type: "number"},
				},
			},
			{
				Name: "ServerData",
				Fields: []StructField{
					{Name: "Config", JSONName: "config", Type: "Config"},
					{Name: "Title", JSONName: "title", Type: "string"},
				},
			},
		},
	}

	got := GenerateDTS(rf)

	expectations := []string{
		"declare namespace Settings {",
		"  interface Config {",
		"    theme: string;",
		"    fontSize: number;",
		"    beta: boolean;",
		"    score: number;",
		"  interface ServerData {",
		"    config: Config;",
		"    title: string;",
	}

	for _, exp := range expectations {
		if !strings.Contains(got, exp) {
			t.Errorf("output missing %q\n\nFull output:\n%s", exp, got)
		}
	}
}

func TestGenerateDTS_NestedRoute(t *testing.T) {
	rf := RouteFile{
		Dir:     "users/profile",
		Package: "profile",
		Funcs: []RouteFunc{
			{
				Name:       "SSR",
				ReturnType: "ServerData",
			},
		},
		Structs: []StructDef{
			{
				Name: "ServerData",
				Fields: []StructField{
					{Name: "Name", JSONName: "name", Type: "string"},
				},
			},
		},
	}

	got := GenerateDTS(rf)

	if !strings.Contains(got, "declare namespace UsersProfile {") {
		t.Errorf("expected namespace UsersProfile, got:\n%s", got)
	}
}

func TestGenerateRuntimeModule(t *testing.T) {
	rf := RouteFile{
		Dir:     "dashboard",
		Package: "dashboard",
		Funcs: []RouteFunc{
			{
				Name:       "SSR",
				ReturnType: "ServerData",
			},
		},
		Structs: []StructDef{
			{
				Name: "ServerData",
				Fields: []StructField{
					{Name: "Posts", JSONName: "posts", Type: "Post[]"},
					{Name: "Author", JSONName: "author", Type: "Author"},
				},
			},
		},
	}

	got := GenerateRuntimeModule(rf)

	expectations := []string{
		"// Code generated by rstf. DO NOT EDIT.",
		"let _data: Record<string, any> = {};",
		"export function serverData(): Dashboard.ServerData {",
		"return _data as Dashboard.ServerData;",
		"export function __setServerData(data: Record<string, any>) {",
		"_data = data;",
	}

	for _, exp := range expectations {
		if !strings.Contains(got, exp) {
			t.Errorf("output missing %q\n\nFull output:\n%s", exp, got)
		}
	}
}

func TestNamespace(t *testing.T) {
	tests := []struct {
		dir  string
		want string
	}{
		{".", "Main"},
		{"dashboard", "Dashboard"},
		{"settings", "Settings"},
		{"users/profile", "UsersProfile"},
		{"admin/users/edit", "AdminUsersEdit"},
	}
	for _, tt := range tests {
		got := Namespace(tt.dir)
		if got != tt.want {
			t.Errorf("Namespace(%q) = %q, want %q", tt.dir, got, tt.want)
		}
	}
}
