package codegen

import (
	"fmt"
	"path/filepath"
	"strings"
	"unicode"
)

// Namespace returns the PascalCase namespace name for a route directory path.
// Examples: "dashboard" -> "Dashboard", "users/profile" -> "UsersProfile",
// "auth/forgot-password" -> "AuthForgotPassword"
func Namespace(dir string) string {
	if dir == "." {
		return "Main"
	}
	parts := strings.Split(filepath.ToSlash(dir), "/")
	var result strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		for _, seg := range strings.FieldsFunc(part, func(r rune) bool {
			return !unicode.IsLetter(r) && !unicode.IsDigit(r)
		}) {
			result.WriteString(ucFirst(seg))
		}
	}
	return result.String()
}

// GenerateDTS produces a TypeScript declaration file (.d.ts) with a declare namespace
// for a parsed RouteFile. The types are globally available without imports.
func GenerateDTS(rf RouteFile) string {
	ns := Namespace(rf.Dir)
	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "declare namespace %s {\n", ns)

	// Write interfaces for each struct (including the ServerData return type).
	for i, sd := range rf.Structs {
		fmt.Fprintf(&b, "  interface %s {\n", sd.Name)
		for _, f := range sd.Fields {
			fmt.Fprintf(&b, "    %s: %s;\n", f.JSONName, f.Type)
		}
		b.WriteString("  }\n")
		if i < len(rf.Structs)-1 {
			b.WriteString("\n")
		}
	}

	b.WriteString("}\n")
	return b.String()
}

// GenerateRuntimeModule produces the rstf/generated/{path}.ts module for an
// SSR-backed component. The module exports a typed SSR wrapper bound to the
// component's generated path so user code never needs to author component IDs.
func GenerateRuntimeModule(rf RouteFile, componentPath string) string {
	var fn *RouteFunc
	for i := range rf.Funcs {
		if rf.Funcs[i].Name == "SSR" {
			fn = &rf.Funcs[i]
			break
		}
	}
	if fn == nil {
		return "// Code generated by rstf. DO NOT EDIT.\n"
	}

	ns := Namespace(rf.Dir)

	// Verify the return struct exists.
	found := false
	for _, s := range rf.Structs {
		if s.Name == fn.ReturnType {
			found = true
			break
		}
	}
	if !found {
		return "// Code generated by rstf. DO NOT EDIT.\n"
	}

	var b strings.Builder
	b.WriteString("// Code generated by rstf. DO NOT EDIT.\n")
	if rf.Dir == "." {
		b.WriteString("import type { PropsWithChildren } from \"react\";\n")
	}
	b.WriteString("import { createSSRWrapper } from \"@rstf/ssr\";\n\n")

	ssrPropsType := SSRPropsTypeName(rf.Dir)
	if rf.Dir == "." {
		fmt.Fprintf(&b, "export type %s = PropsWithChildren<%s.%s>;\n", ssrPropsType, ns, fn.ReturnType)
		fmt.Fprintf(&b, "export const SSR = createSSRWrapper<%s.%s>(%q);\n", ns, fn.ReturnType, componentPath)
	} else {
		fmt.Fprintf(&b, "export type %s = %s.%s;\n", ssrPropsType, ns, fn.ReturnType)
		fmt.Fprintf(&b, "export const SSR = createSSRWrapper<%s.%s>(%q);\n", ns, fn.ReturnType, componentPath)
	}

	return b.String()
}

func SSRPropsTypeName(dir string) string {
	return Namespace(dir) + "SSRProps"
}
